GetDKAN/dkan

- drupal-org.make
- test/features/panels.feature
Issue #333: Updating admin_menu to 3.0-rc5
> Updating admin_menu on dkan build

- build-dkan.make
- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.module
- test/behat.yml
- test/features/home.feature
> Janette internal 374

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
Adds "auth user" to dataset view.
> Fixes dataset view for logged in user

- drupal-org.make
> Updating nuboot_radix to latest 7.x-1.x

- modules/dkan/dkan_sitewide/dkan_sitewide.module
> 411 move colorizer message to dkan sitewide

- drupal-org.make
- test/features/recline.feature
> Freezing nuboot_radix to latest 7.x-1.x

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_user/dkan_sitewide_user.views_default.inc
Unpublished nodes should not be viewable on /dataset and on groups and users.
> Unpublished nodes not viewable in views

- drupal-org-core.make
> Updating core to 7.36

- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.module
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_demo_front/dkan_sitewide_demo_front.module
QA -  testing 508 updates to dkan_dataset, dkan_sitewide, and nuboot_radix
> 464 508 compliance

- drupal-org.make
Colorizer maintainer will not merge patches so updating make file.
> 385 colorizer updates

- README.md
> Proposed update to explain relases vs release candidates

- drupal-org.make
Pulls in:
* NuCivic/nuboot_radix#17
* NuCivic/nuboot_radix#18
* NuCivic/nuboot_radix#19
> Latest nuboot_radix with dropdown and button color improvements

- build-dkan.make
- drupal-org.make
> 483 array flip entity warning

- drupal-org.make
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.info
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.strongarm.inc
Updates to dkan_sitewide_roles_perms for user photo
> 116 user photo

- drupal-org.make
Don't merge until test passes.
> Update panels to 3.5

- modules/dkan/dkan_sitewide/dkan_sitewide.module
> Only render register button if registration is open

- dkan.info
- dkan.profile
- drupal-org.make
NuCivic/dkan#341
NuCivic/nucivic-internal#160
> Adding honeypot to dkan

- drupal-org.make
* Added the default to drupal.org.make and removed any unecessary setting of subdir = contrib.
> Issue #505: Make files support setting a default subdir, so use it.

- drupal-org.make
> NuCivic/internal#678: Remove duplicated inclusion of libraries.

- .travis.yml
- test/behat.yml
- test/features/bootstrap/FeatureContext.php
- test/features/data_dashboard.feature
> NuCivic/internal#670: Added tests for Data Dashboards.

- dkan.install
- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.info
• Disable bartik and seven themes
• Update dkan_sitewide.info
> NuCivic/internal#717 Add conditional styles module

- .travis.yml
Upgrades travis. See: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
> Upgrades travis

- dkan.profile
- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.module
> updated colorize to 1.7  #641

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.strongarm.inc
> Fixed problem with role default to administrator after new install #151

- drupal-org.make
> Internal 701 security updates

- dkan.info
- drupal-org.make
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.strongarm.inc
> Added adminrole to main makefile #534

- drupal-org.make
> Test out new versions of autocomplete_deluxe and panopoly_widgets

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.info
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
> NuCivic/internal#618 Add filterable dataset view pane option

- test/README.md
Added instructions to get behat tests running locally.
> NuCivic/internal#724: Added README.md to test

- dkan.info
> Fix missing dependencies in dkan.info

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_profile_page/dkan_sitewide_profile_page.features.menu_links.inc
Under content in the user command center
> NuCivic/internal#764 Change link title to "Manage content"

- .gitignore
- drupal-org.make
- patches/panopoly_widgets_add_jquery_ui_tabs.patch
- test/features/widgets.feature
NuCivic/internal#759: Adds patch to explicitly add jquery.ui.tabs.js from jquery_update module
> Patch for panopoly spotlight widget

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.user_permission.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.info
- test/features/bootstrap/FeatureContext.php
- test/features/data_dashboard.feature
> Behat test for filtered dataset view pane on dashboards

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
> Update Social blocks

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.info
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.features.inc
> Issue #656 removes dataset list from panel page and restores Resource blocks

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_profile_page/dkan_sitewide_profile_page.pages_default.inc
ref #649 
Create second user, "test."
> #649 Restore public user page when looking at other users

- CONTRIBUTING.md
- drupal-org-core.make
- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.info
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_profile_page/dkan_sitewide_profile_page.pages_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.strongarm.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.features.inc
ref #658 
This is currently blocked because of https://github.com/NuCivic/dkan/issues/649
> Issue #658 Make user profile image no longer blurry

- drupal-org.make
> Upgrade fieldable_panels_panes to 1.7

- dkan.install
- dkan.profile
SSH into nansen and run the following in mysql console:
```
drop database `706-site-i`;
create database `706-site-i`;
```
> #706 Replace existing site install with batch process

- .travis.yml
> Remove artifacts from .travis.yml for now

- .travis.yml
This should result in any PR branch being run, but only that branch.
> Try only building 7.x-1.x to avoid building branches twice.

- modules/dkan/dkan_sitewide/dkan_sitewide.module
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_profile_page/dkan_sitewide_profile_page.module
- test/features/bootstrap/FeatureContext.php
- test/features/gravatar.feature
Ref: https://github.com/NuCivic/internal/issues/779
> User photo issues

- drupal-org-core.make
> Upgrade to Drupal 7.41

- test/behat.yml
- test/features/bootstrap/FeatureContext.php
- test/features/dataset.feature
This simply adds tests for the changes added in NuCivic/dkan_dataset#167. Acceptance test is tests pass.
> 879 open with preview

- build-dkan.make
- test/features/dataset.feature
This test should fail initially.
> Creates test for additional info

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.install
> Fix upgrade error on dkan_sitewide_roles_perms

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.features.inc
- test/features/dataset.feature
See #748 
1. Create Data dashboard
2. It should not appear in /datasets page
> 748 search bug

- test/behat.yml
- test/circle-install.sh
- test/composer.lock
- test/features/dataset.author.feature
- test/features/groups.feature
- test/features/user.admin.feature
- test/features/user.all.feature
> Dev 807 dkan command center test

- build-dkan.make
- drupal-org.make
> Issue #590 Fix group pager

- drupal-org.make
- patches/cross-site-scripting-facets-156778.patch
> Fix Cross-site scripting (XSS) vulnerability #790

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.user_permission.inc
Ref https://jira.govdelivery.com/browse/CIVIC-663
###Acceptance:###
> Add the cancel account perm to authenticated user.

- drupal-org.make
Fix problem with cache and fontyourface
ref #613
> Added patch to fontyourface

- .probo.yml
Rebased to cleanup the test commits, ready to merge into dev-dkan-ahoy (which can then be merged into 7.x-1.x)
> Civic 1127 probo dkan ahoy

- drupal-org.make
- patches/fontyourface-no-ajax-browse-view.patch
1. Browse to admin/appearance/fontyourface. 
2. Go to a page other than the first page. 
3. The fonts should still preview correctly.
> Remove ajax to make fontyourface browsing work

- .ahoy/dkan.ahoy.yml
- .ahoy/docker.ahoy.yml
- .probo.yml
- circle.yml
- dkan-init.sh
- test/behat.yml
Use dkan-init.sh to install most dependencies and run the ahoy dkan commands to fully install a site.
> Dev dkan ahoy smarter

- test/composer.lock
* Adds support for workbench_moderation need for global user.
> Update to the latest dkanextension

- test/features/user.admin.feature
... and subsequen tests to fail.
> Fix typo which caused temp users to not be cleaned up 

- test/composer.lock
Created to update dkanextension to it latest version.
> Updated dkanextension.

- .ahoy/site.ahoy.yml
Now it expects dkan at the gitroot of the repo
Issue #CIVIC-1399
> Refactors ahoy site remake and post-build

- .ahoy/site.ahoy.yml
Ref civic-1396
Just a quick tweek to make the api more regular.
> Tweek the api for site asset commands.

- test/composer.json
- test/composer.lock
PR created to restore the dkanextension branch.
> Behat upgrade to 3.1

- README.md
Issue: None
Bad markdown in README.md 
- N/A
- N/A
None
> Fix markdown in root README.md

- CHANGELOG.txt
- drupal-org.make
Security update for Fieldable Panels Panes
> Add security update for Fieldable Panels Panes 1.7 > 1.8

- .ahoy/docker.ahoy.yml
Read http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/
> Adds docker cleanup command

- .ahoy/docker.ahoy.yml
This reverts commit f0ddddc60893f52acf3e91f130353a8848f1b42d.
> Revert "Allow users to run `ahoy docker exec` in all cases."

- CHANGELOG.txt
> Civic-2135 update changelog file

- test/features/markdown_editor.feature
Just a slight modification to #1085
> Abbreviate tests

- .ahoy/theme.ahoy.yml
> civic-2697 fixing ahoy dkan theme commands

- .ahoy/dkan.ahoy.yml
- test/composer.json
- test/composer.lock
- test/features/recline.feature
Issue: https://jira.govdelivery.com/browse/CIVIC-2696
> Point to fixed dkanextension version

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.features.menu_links.inc
Should work just like in #1086
> Fix typo in add data story link

- dkan.profile
> Fix merge breaking markdown setup

- CHANGELOG.txt
- drupal-org-core.make
> Upgrade Drupal core to 7.44

- .ahoy/dkan.ahoy.yml
- .ahoy/docker.ahoy.yml
- .ahoy/starter.ahoy.yml
- .probo.yml
- dkan-init.sh
Add test users for basic DKAN roles to probo sites
> Test users in probo script

- modules/dkan/dkan_permissions/dkan_permissions.features.roles_permissions.inc
Fixes #1209 
* Click "RDF" button on any dataset and see if it works
> Add restws permissions for anonymous users

- CHANGELOG.txt
- drupal-org-core.make
> Update Drupal core to 7.50

- CHANGELOG.txt
- drupal-org.make
> Restws upgrade

- CHANGELOG.txt
- drupal-org-core.make
- drupal-org.make
- modules/dkan/dkan_permissions/dkan_permissions.features.roles_permissions.inc
- test/features/dataset.all.feature
> Latest patch releases back into DKAN core

- modules/dkan/dkan_topics/dkan_topics.module
- modules/dkan/dkan_topics/theme/dkan_topics.css
Updating release branch with icons for topics menu.
> Add icons to topics menu - release branch

- test/composer.lock
Issue: CIVIC-3454
Upgrades guzzle in response to CVE-2016-5385: https://httpoxy.org/
> Updates composer.lock to include latest version of guzzle

- test/features/recline.feature
This updates the files in the recline.feature file to use s3.
> Update recline.feature to use s3

- test/features/datastore.feature
- test/features/recline.feature
There are some tests that don't have the tag @noworkflow and they need it.
> Add noworkfow tags to datastore and recline tests.

- CHANGELOG.txt
- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.module
- modules/dkan/dkan_sitewide/includes/dkan.utils.inc
- test/features/recline.feature
https://jira.govdelivery.com/browse/CIVIC-3678
https://github.com/NuCivic/dkan/issues/738
It's a refactor of the original previews PR.
dkan_dataset#previews
recline#previews
> Add recline previews

- CHANGELOG.txt
Use **Acceptance Criteria** from https://github.com/NuCivic/dkan_workflow/pull/46
~~https://github.com/NuCivic/dkan_workflow/pull/34~~
https://github.com/NuCivic/dkan_workflow/pull/46
> Workflow update legend release branch

- drupal-org.make
Actual merge to be done on NuCivic/dkan_dataset#265
> Point to dkan_dataset explorer-canvas-move branch for QA

- modules/dkan/dkan_topics/dkan_topics.module
REF CIVIC-4001
REF #1344
AC
==
> Fix path path to topics image.

- CHANGELOG.txt
- drupal-org.make
- test/features/group.admin.feature
Adds a test for new default group image
https://github.com/NuCivic/dkan_dataset/pull/268
> Default group img

- test/composer.json
- test/features/dataset.all.feature
Will depend on: https://github.com/NuCivic/dkanextension/pull/60
REF CIVIC-3950
Acceptance Tests
==
> Use exact text for Author test.

- .ahoy/docker-compose.yml
REF CIVIC-3947
Updates the docker web container with clamav.
Updates the docker browser container to have access to project.
Acceptance Tests
===
> Update docker containers:

- circle.yml
- modules/dkan/dkan_topics/dkan_topics.make
This tests CirlceCi and a patch to entity_path for MySQL 5.7.
> Support mysql 5.7

- CHANGELOG.txt
- drupal-org.make
Issue: civic 4170
1. - On any resource, click 'Edit'
2. - Make a change to any field
3. - Click 'View Changes'
https://github.com/NuCivic/dkan_dataset/pull/277
> QA for dkan_dataset branch: form-redirect-bugs-release

- circle.yml
- modules/dkan/dkan_migrate_base/dkan_migrate_base_data_json.inc
- modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/dkan_migrate_base_example.info
- test/composer.lock
- test/phpunit/DKANMigrateBaseTest.php
- test/phpunit/boot.php
#1387
@janette ask me to bring the changes in NuCivic/dkan_migrate_base#35 to this consolidation branch
This also:
+ Updates composer.lock to install phpunit
+ Fixes boot.php docroot path (so phpunit knows where to find drupal)
+ Sets circle to run tests in dkan/test/phpunit
> Consolidation - Updates dkan migrate base

- .ahoy/dkan.ahoy.yml
- circle.yml
- test/features/dataset.admin.feature
- test/features/dataset.all.feature
- test/features/dataset.author.feature
- test/features/dataset.editor.feature
- test/features/group.all.feature
- test/features/group.author.feature
- test/features/group.editor.feature
- test/features/profile.feature
- test/features/resource.admin.feature
- test/features/resource.all.feature
- test/features/resource.author.feature
- test/features/resource.editor.feature
- test/features/user.admin.feature
- test/features/user.all.feature
- test/features/user.author.feature
Remove javascript tags from tests when it's no needed. Also improve drush make by using concurrency.
> Improve tests performance

- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.info
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.strongarm.inc
Removes jquery update setting from dkan_dataset
We are setting the value on install to 1.10
> Jquery update fix

- .ahoy/docker-compose.yml
- circle.yml
REF CIVIC-4386
Fixes potential testing failure with widget.feature
QA Steps
===
> Update version of selenium chrome driver.

- .ahoy/dkan.ahoy.yml
- circle.yml
- dkan.profile
- test/features/data_story.author.feature
- test/features/dataset.admin.feature
REF https://jira.govdelivery.com/browse/CIVIC-1920.
REF https://jira.govdelivery.com/browse/CIVIC-4153
Increases the allowed time with no output per test command to 15 minutes.
Acceptance
=========
> Avoid selenium spawn chrome again

- .ahoy/docker-compose.yml
> Pin cli container.

- themes/nuboot_radix/README.md
- themes/nuboot_radix/scss/nuboot_radix.style.scss
Adds extra notes on the README.md
> Update theme documentation

- modules/dkan/dkan_harvest/dkan_harvest.pages.inc
> Fix event id sort column

- CHANGELOG.txt
- modules/dkan/dkan_harvest/dkan_harvest.info
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/dkan_harvest_dashboard.views_default.inc
> Add sorting to orphan and published columns

- .ahoy/.scripts/active_theme_path.php
- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/behat.sh
- .ahoy/.scripts/circle-behat-balancer.rb
- .ahoy/.scripts/circle-behat.rb
- .ahoy/.scripts/dkan-make.sh
- .ahoy/.scripts/dkan-si.sh
- .ahoy/.scripts/dkan-test.rb
- .ahoy/.scripts/drupal-rebuild.sh
- .ahoy/dkan.ahoy.yml
- .ahoy/docker-compose.yml
- .ahoy/docker.ahoy.yml
- .ahoy/theme.ahoy.yml
- circle.yml
There have been some changes to dkan 7.x-1.x  regarding some enhancements to speed up tests and to reduce timeous on Circle that have only taken place in 7.x-1.x.  The changes include:
* https://github.com/SeleniumHQ/docker-selenium/issues/87
+    DBUS_SESSION_BUS_ADDRESS: /dev/null
* Increasing time allowed per steps to 1200 seconds
* Adding a load balancer feature to .ahoy scripts to better balance tests across containers (we will replace this with junit output that circle can handle itself in the future).
> Backport 7.x-1.x test enhancements and .ahoy

- drupal-org.make
- test/features/panels.feature
> Update ctools and update tests

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
> Set html format for harvested resource in the body field

- CHANGELOG.txt
- modules/dkan/dkan_fixtures/modules/dkan_default_content/data/package_show?id=florida-bike-lanes.json
- modules/dkan/dkan_topics/dkan_topics.entity_path.inc
> Replace separator in entity paths

- modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/README.md
Issue: CIVIC-4433
Add Riadh's documentation on terminal commands for quickly QAing rest api functionality.
> Update dkan_dataset_rest_api README.md with terminal command examples

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
> Fix space in multiline error message

- .ahoy/site/.scripts/prune-database.php
See: https://github.com/NuCivic/dkan/pull/1469
> Handle null resources

- modules/dkan/dkan_harvest/README.md
Just some mostly-cosmetic improvements to the Harvester readme. Once our new RTD docs site is up, we should probably move the "extending" section in there.
> Improve Harvester docs

- drupal-org-core.make
> Update Drupal core to 7.51

- modules/dkan/dkan_topics/dkan_topics.entity_path.inc
Issue: CIVIC-4675
Related with: https://github.com/NuCivic/dkan/pull/1455
> Use dashes instead of underscore for tags in dkan topics

- modules/dkan/dkan_topics/dkan_topics.entity_path.inc
- modules/dkan/dkan_topics/dkan_topics.facetapi_defaults.inc
- modules/dkan/dkan_topics/dkan_topics.features.features_overrides.inc
- modules/dkan/dkan_topics/dkan_topics.features.field_base.inc
- modules/dkan/dkan_topics/dkan_topics.features.field_instance.inc
- modules/dkan/dkan_topics/dkan_topics.features.inc
- modules/dkan/dkan_topics/dkan_topics.features.taxonomy.inc
- modules/dkan/dkan_topics/dkan_topics.install
- modules/dkan/dkan_topics/dkan_topics.module
- modules/dkan/dkan_topics/dkan_topics.strongarm.inc
- modules/dkan/dkan_topics/dkan_topics.views_default.inc
- modules/dkan/dkan_topics/modules/dkan_default_topics/dkan_default_topics.install
- modules/dkan/dkan_topics/modules/dkan_default_topics/dkan_default_topics.module
- modules/dkan/dkan_topics/theme/dkan_topics.css
Issue: civic-4659
Update code to pass code review on dkan_topics
tests pass
> Code review for dkan_topics

- modules/dkan/dkan_permissions/dkan_permissions.features.roles_permissions.inc
- modules/dkan/dkan_permissions/dkan_permissions.module
Issue: civic-4655
coder review fixes for dkan_permissions
tests pass
> Code review for dkan_permissions

- modules/dkan/dkan_ipe/dkan_ipe.features.inc
- modules/dkan/dkan_ipe/dkan_ipe.install
- modules/dkan/dkan_ipe/dkan_ipe.module
Issue: civic-4653
coder review updates for dkan_ipe module
tests pass
> Code review for dkan_ipe

- modules/dkan/dkan_migrate_base/dkan_migrate_base.install
- modules/dkan/dkan_migrate_base/dkan_migrate_base.migrate.inc
- modules/dkan/dkan_migrate_base/dkan_migrate_base.module
- modules/dkan/dkan_migrate_base/dkan_migrate_base_data_json.inc
- modules/dkan/dkan_migrate_base/dkan_migrate_base_dataset.inc
- modules/dkan/dkan_migrate_base/dkan_migrate_base_group.inc
- modules/dkan/dkan_migrate_base/dkan_migrate_base_resource.inc
- modules/dkan/dkan_migrate_base/grunt_extend/Gruntfile.js
- modules/dkan/dkan_migrate_base/grunt_extend/test.module
- modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/dkan_migrate_base_example.info
- modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/dkan_migrate_base_example.migrate.inc
- modules/dkan/dkan_migrate_base/modules/dkan_migrate_base_example/dkan_migrate_base_example.module
Issue: civic-4654
Update code to pass code review on dkan_migrate_base
tests pass
> Code review updates for dkan_migrate_base

- test/README.md
PHPUnit documentation was added on test/README.md.
> Added PHPUnit documentation.

- CHANGELOG.txt
CIVIC-4880
Fix CHANGELOG.txt by removing conflict notes
> Remove conflict lines from CHANGELOG.txt

- dkan.install
Issue: civic-4423
Need clean up for removed modules and deprecated untracked directories when upgrading to 1.13
> Add hook updates for 1.13 upgrade

- dkan.info
- modules/dkan/dkan_data_dashboard/dkan_data_dashboard.info
- modules/dkan/dkan_data_story/dkan_data_story.info
- modules/dkan/dkan_sitewide/dkan_sitewide.info
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panelizer/dkan_sitewide_panelizer.info
- modules/dkan/dkan_topics/dkan_topics.info
- modules/dkan/dkan_topics/modules/dkan_default_topics/dkan_default_topics.info
- themes/dkan/dkan.info
Issue: CIVIC-4818
Remove all the version numbers from info files in the release branch.
- https://github.com/NuCivic/jenkins_release_n_update_builds/pull/13
> Remove version numbers from info files

- CHANGELOG.txt
- drupal-org.make
- test/features/panels.feature
> Upgrade ctools to 1.11 on release branch

- drupal-org.make
Issue: https://jira.govdelivery.com/browse/CIVIC-1350
Sometimes passing test we are getting some exceptions related with worbench moderation.
1. Check test and sometimes you see exceptions
> Add patch to workbench that fixes Exception. #CIVIC-1350

- .ahoy/.scripts/behat-parse-params.rb
Backport for https://github.com/NuCivic/dkan/pull/1569
> Release 1 12 fix regression behat parse params

- drupal-org.make
- test/dkanextension/src/Drupal/DKANExtension/Context/DKANContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/ResourceContext.php
- test/features/resource.author.feature
> Update dkan extension methods to satisfy embed cache

- CHANGELOG.txt
- drupal-org.make
Issue: civic-5018
Update file_entity module 
tests pass
> Update file_entity to 2.0-beta3 CIVIC-5018

- CHANGELOG.txt
- drupal-org.make
- modules/dkan/dkan_topics/dkan_topics.install
- patches/panopoly_widgets_add_jquery_ui_tabs.patch
- patches/panopoly_widgets_overrides.patch
- test/features/widgets.feature
- themes/nuboot_radix/includes/form.inc
Issue: CIVIC-5018
panopoly_widgets 1.37 > 1.41 (+ 2 re-rolled patches)
panoploy_images 1.37 > 1.41
media 2.0-beta1 > 2.0-beta13
Tests pass
> Update panopoly and media modules CIVIC-5018

- test/features/widgets.feature
Issue: None
This fix is needed in order for steps to pass on DKAN Starter.
- Tests should pass.
> Added missing step on widgets feature.

- CHANGELOG.txt
- drupal-org.make
Issue: Civic-5054
Security update for the media module
> Upgrade media module to 2.0-beta13 CIVIC-5054

- CHANGELOG.txt
- drupal-org-core.make
Responds to https://www.drupal.org/SA-CORE-2016-005
> Update Drupal to 7.52

- modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php
- test/features/resource.author.feature
- test/phpunit/boot.php
- test/phpunit/dkan_dataset/files/gold_prices_states.csv
- test/phpunit/dkan_dataset/reclineEmbedCacheTest.php
- test/phpunit/phpunit.xml
Issue: civic-5096
Acceptance criteria
===================
> Replace recline embed cache behat tests with phpunit

- test/features/widgets.feature
Test relies on default content that is not always available.
QA Steps
===
> Use background asset.

- modules/dkan/dkan_harvest/README.md
Issue: CIVIC-5160
Add documentation of the recently added dkan_harvest options.
> Add docs to the added harvest drush options [CIVIC-5160]

- CHANGELOG.txt
Issue: CIVIC-5212
Redirect fix was unclear on release notes
> Clarify form redirect fix on CHANGELOG.txt CIVIC-5212

- CHANGELOG.txt
- drupal-org.make
Issue CIVIC-5312
Testing the 1.0 release of Visualization Entity module on DKAN 1.13
> Use 1.0 release of visualization entity module in 1.13

- .github/PULL_REQUEST_TEMPLATE.md
Issue: CIVIC-4894
During the Mars retrospective on 11/14 we tried to clarify what should be included in PRs. We should review the template and make sure it only contains the necessary information.
- tests
- changelog
- issue reference
- PR dependencies
- QA steps
- coder check
> Update pull request template CIVIC-4894

- CHANGELOG.txt
- drupal-org.make
Issue: CIVIC-5603
https://github.com/NuCivic/nuboot_radix/pull/103
> QA release update on nuboot_radix

- test/features/pod.feature
REF CIVIC-5613
Allow for this test to be skipped by site.
QA Steps
==
> Add unique tag to POD test

- CHANGELOG.txt
- drupal-org-core.make
> Update Drupal core to 7.54

- CHANGELOG.txt
Issue: CIVIC-5708
Updates the CHANGELOG.txt with references to PR#s
> Add PR references to CHANGELOG.txt CIVIC-5708

- docs/introduction/installation.rst
This fixes the DKAN starter link.
> Fix DKAN Starter link

- test/features/pod.feature
> Allow for this test to be skipped by site.

- docs/releases/notes/1.13.1.md
Just adding release notes to docs for 1.13.1 release.
> Release notes for 1.13.1

- docs/releases/notes/1.13.md
Issue: CIVIC-5773
This makes a number of changes to the DKAN 1.13 release notes based on a review of various documentation sources to ensure that the release notes correctly capture all UX changes.
> CIVIC-5773: revisions to 1.13 release notes

- test/features/dataset.all.feature
Issue: CIVIC-5746
Sorry @dkinzer  missed this one on the last PR
> Tag test that requires the main menu CIVIC-5746

- test/features/topics.feature
The 'no-main-menu' tag was added on Topic tests.
> Added 'no-main-menu' tag on tests.

- CHANGELOG.txt
- drupal-org.make
Issue: CIVIC-5786
Security update for views, remove patch no longer needed.
Tests pass
> Update views to 3.15 CIVIC-5786

- CHANGELOG.txt
Update changelog with the new version 7.x-1.12.14.
> Updated changelog to version 7.x-1.12.14

- docs/releases/notes/1.13.2.rst
Issue: CIVIC-6024
Release notes for 1.13.2 should include everything that was addressed in the release.
> Update release notes for 1.13.2 CIVIC-6024

- docs/releases/notes/1.12.14.md
- docs/releases/notes/index.rst
Issue: CIVIC-6030
Adding release notes for 1.12.14 to RTD
> Keep release notes in sync CIVIC-6030

- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/circle-behat.rb
- .ahoy/.scripts/dkan-test.rb
- .ahoy/tests/behat-parse-params.rb
- test/behat.yml
REF https://jira.govdelivery.com/browse/CIVIC-5758
This is needed in order to use latest .ahoy tools locally and on circle.
> Update ahoy-tools for 1.12.14

- dkan.profile
> Fix module_load_include statement.

- modules/dkan/dkan_dataset/dkan_dataset.module
> dkan_dataset module is trying to load dkan-flaticon.css when this file is now moved to nuboot_radix

- CHANGELOG.txt
- drupal-org.make
REF CIVIC-5969
https://www.drupal.org/node/2851567
https://www.drupal.org/node/2406863
> Patch rules_init cache process.

- CHANGELOG.txt
- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.views_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
Reverts NuCivic/dkan#1813. Should have gone on release branch.
> Revert "Update the groups page view to sort alphabetically CIVIC-5990"

- .ahoy/.scripts/dkan-lint.sh
- .ahoy/dkan.ahoy.yml
- circle.yml
- dkan.install
- dkan.profile
- test/composer.json
- test/composer.lock
Re-roll of #1512 
REF https://jira.govdelivery.com/browse/CIVIC-4817
Let's enforce code standards by not only supporting coder in ahoy, but adding a test that there are no code sniffer errors for drupal when we build in Circle
QA Steps
===
> Add php linting for submitted PR to circle

- CHANGELOG.txt
- docs/components/dataset/usage.rst
Issue: CIVIC-5906
This PR adds CHANGELOG message and documentation updates for NuCivic/recline#89
> Documentation updates for changes to preview logic

- CHANGELOG.txt
- drupal-org.make
Issue: CIVIC-6227
The "media" module was updated to 2.0
> Upgrade media module to 2.0

- drupal-org.make
Need to keep 1.14 chart updates out of 1.13.4
> Use 1.13.4 branch of visualization_entity

- CHANGELOG.txt
- drupal-org.make
Security update https://www.drupal.org/node/2877316
> Upgrade to media 2.1

- docs/apis/rest-api.rst
Fixed the spelling in the note to match what is written in the code snippet.
Issue: link_to_jira_github_issue
It's a spelling issue, pretty sure there's no need to test anything.
> Fixed spelling.

- dkan.install
Fixes error introduced in #1880
> Correct hook_update_N function name on dkan.install

- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.views_default.inc
- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- modules/dkan/dkan_migrate_base/dkan_migrate_base.migrate.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
- modules/dkan/open_data_federal_extras/fed_bureau_code_list/list_to_array.php
- modules/dkan/open_data_federal_extras/fed_bureau_code_list/omb-agency-bureau-treasury-codes.php
Issue: CIVIC-6461
Tests are failing for 1.13.4 because of coder issues. This PR was created to fix them.
> Fix coder issues.

- modules/dkan/dkan_harvest/dkan_harvest.module
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/dkan_harvest_dashboard.module
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/dkan_harvest_dashboard.views_default.inc
- modules/dkan/dkan_permissions/dkan_permissions.features.roles_permissions.inc
Fix a typo on dkan_permissions
> Fix typo on dkan_harvest permissions

- drupal-org.make
Ref: https://github.com/NuCivic/dkan/pull/1950
> Upgrade feeds to latest revision

- drupal-org.make
> Upgrade feeds to latest revision (#1959)

- test/features/datastore_fast_import.feature
This removes a test line that was breaking and is no longer necessary. Tests should pass on DKAN starter before merging.
See NuCivic/dkan_starter#320
> Remove "import files using batch imports" tests

- CHANGELOG.txt
- drupal-org.make
Fixes Services - Critical - SQL Injection - SA-CONTRIB-2017-054
https://www.drupal.org/project/services/releases/7.x-3.20
REF: https://jira.govdelivery.com/browse/CIVIC-6566
> Security update for services module.

- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/circle-behat.rb
- .ahoy/.scripts/config.rb
- .ahoy/.scripts/dkan-lint.sh
- CHANGELOG.txt
- drupal-org.make
- test/dkanextension/src/Drupal/DKANExtension/Context/DatasetContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANEntityContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/ServicesContext.php
Add test updates from the dev branch.
#1963 
#1938
> Pull in updates to dkanextension for required fields

- drupal-org.make
Issue: None
Update 'recline' and 'open_data_schema_map' branches from 1.13.4 to 1.13.5.
> Update module branches from 1.13.4 to 1.13.5

- drupal-org.make
- test/features/widgets.feature
> 1.13.6 module updates

- modules/dkan/dkan_sitewide/dkan_sitewide.module
Remove files_resup module update notices.
> Add file_resup to the list of up to date projects

- README.md
Added license information to readme file.
> Licensing info in README

- test/features/dataset.all.feature
Allow users to skip specific dataset.all.features scenarios via tags.
> Tag dataset.all.feature scenarios.

- drupal-org.make
Addresses security vulnerability [DRUPAL-SA-CONTRIB-2017-068](https://www.drupal.org/node/2902604)
> Update views to 3.17

- CHANGELOG.txt
- drupal-org.make
Security update for [DRUPAL-SA-CONTRIB-2017-067](https://www.drupal.org/node/2902596)
> Update entityreference to 1.5

- CHANGELOG.txt
- docs/releases/notes/1.13.7.md
Just release notes, that's it.
> Release ntoes for 1.13.7

- CHANGELOG.txt
- docs/releases/notes/1.13.7.md
Issue: None
Fixed release notes generated on https://github.com/NuCivic/dkan/pull/2065
> Fixed release notes for 1.13.7

- drupal-org.make
Connects #2100
QA Steps
==
- Click on probo link and review install logs.
> Apply search_api_db patch; fix hook_update failure.

- test/features/datastore.feature
- test/features/resource.admin.feature
- test/features/resource.author.feature
- test/features/resource.editor.feature
Still having issues with datastore tests. 
- Using separate files should avoid race issues on datastore tables being dropped when other scenarios are trying to use them.
- Adding @datastore tag to clean up after scenarios
- Adding unique tags to resource.author.feature
> Update datastore tests

- CHANGELOG.txt
- README.md
- dkan.install
- docs/index.rst
- docs/introduction/installation.rst
- docs/introduction/maintaining.rst
- modules/dkan/dkan_fixtures/modules/dkan_default_content/data/page_show%3Fid=f2e6698b-4406-47ca-9cf4-af8016ffa411.json
- themes/nuboot_radix/includes/structure.inc
- themes/nuboot_radix/theme-settings.php
Connects #2160 
Connects #2170
> 2160 remove video content

- README.md
@lukefretwell re-wrote the readme file - review and merge!
> Re-write of README file

- docs/apis/rest-api.rst
Issue: link_to_jira_github_issue
Added a "DELETE node" HTTP request example.
If users want to know how to delete a node, they can find the general process here.
> Added DELETE Node Example

- .github/PULL_REQUEST_TEMPLATE.md
Some tweaks to the template for DKAN pull requests.
> Updates to PR template

- docs/releases/notes/1.14.md
- docs/releases/notes/index.rst
> Add 1.14 release notes to docs

- modules/dkan/dkan_harvest/dkan_harvest.module
> Fix typo in harvest source delete instructions

- docs/introduction/dkan-sites.rst
> Added Telangana Open Data

- docs/introduction/dkan-sites.rst
> Add Barcelona Diputation to sites list

- modules/dkan/dkan_datastore/includes/DkanDatastore.inc
Broken link on datastore pages.
> Fix documentation link for datastore API

- docs/_static/css/custom.css
- docs/conf.py
> Add custom css to docs

- CHANGELOG.txt
- dkan.info
- drupal-org.make
> Added composer_manager to drupal-org.make

- docs/admin/sitemanagermaintenance
Connects https://github.com/GetDKAN/dkan/issues/2313
> Site Manager Monthly Maintenance checklist

- CHANGELOG.txt
> Changelog for the 1.14.2 patch release.

- drupal-org.make
1.8 > 1.9 
https://www.drupal.org/project/entity/releases/7.x-1.9
> Security update for Entity API

- drupal-org-core.make
Responding to [sa-core-2018-001](https://www.drupal.org/sa-core-2018-001)
> Update Drupal core to 7.57

- themes/nuboot_radix/includes/panel.inc
Address the Undefined offset error on nuboot_radix/includes/panel.inc line 45
> Check  var is set

- docs/index.rst
- docs/installation/basic.rst
- docs/installation/index.rst
- docs/installation/local-dev.rst
- docs/introduction/get-dkan.md
- docs/introduction/index.rst
There is still a lot to be done to clean up the documentation of installation and dev practices, but this is a start looking toward open data day and all the participation we're expecting.
> Installation instructions for ahoy

- README.md
Just correcting some bad links.
> Issue #2449: Incorrect Readme Links

- CHANGELOG.txt
> Updates the changelog in preparation for 1.14.6.

- modules/dkan/dkan_sitewide/dkan_sitewide.features.filter.inc
connects #2510 
As a user I want to able to add tables to fields using the markdown html format.
> Add table tags to list of allowed html

- drupal-org.make
- patches/panopoly_widgets_add_jquery_ui_tabs.patch
- patches/panopoly_widgets_overrides.patch
- test/features/resource.editor.feature
> Update contrib modules

- .circleci/config.yml
Code linting should happen before running tests
> Run linting before tests

- docs/components/dataset/datasetfeatures.rst
Small improvement to docs to call out new functionality
> Add an example on how to set the dkan_map_tile_url variable

- .circleci/config.yml
Keeping the harvest phpunit tests commented out as they need work see https://github.com/GetDKAN/dkan/issues/2301
> Restore circleci behat testing

- drupal-org.make
Security update https://www.drupal.org/sa-contrib-2018-045
> Update uuid to 1.1

- docs/components/workflow.rst
Updated workflow.rst to fix bad spelling/grammar; please let me know how new doc is, and whether it's easily understood
Connects https://github.com/NuCivic/dkan_management/issues/88
> Updating workflow.rst to fix bad spelling/writing

- docs/components/storytelling.rst
> Add iframe instructions to documentation

- docs/components/harvest.rst
- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
- test/phpunit/boot.php
- test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
- test/phpunit/phpunit_redirect_test.php
Sometimes harvested resources will have an effective url that includes a query, and the query will block future functionality of the link
data.json URL: https://data.cnra.ca.gov/dataset/49a377cd-f986-416f-a8c4-d0427fa29ecb/resource/10b6256a-089c-49e7-ae2d-c16c4e42f850/download/intertidal-class-area-and-percentage-by-scr-subregion.pdf
Effective URL: https://cnra-assets.s3.amazonaws.com/resources/10b6256a-089c-49e7-ae2d-c16c4e42f850/intertidal-class-area-and-percentage-by-scr-subregion.pdf?Signature=wPR6jQRkfS9hnsQ3KxOcV7U%2Fzss%3D&Expires=1530648536&AWSAccessKeyId=AKIAJYVFNGCJL75FNKXA
Removing the query portion OR Saving the url from the .json file will keep the file available for future downloads (previews will still not work). After testing several harvest sources there does not seem to …
> Change remote file url handling when harvesting

- docs/components/workflow.rst
Connects https://github.com/NuCivic/dkan_management/issues/88
> Final Workflow content improvements

- test/phpunit/dkan_dataset/DataJsonTest.php
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/DkanHarvestTest.php
- test/phpunit/phpunit.xml
connects #2301 
This restores most of the tests but a few still need work. Documented in the ticket.
> Restore working harvest tests

- docs/admin/data_and_content/adding_new_content.rst
Cut out very wordy language; unnecessary "sales" type jargon.
Description. Please write any background information about this PR you think is useful for the product team. Use any of the items below that are relevant to this pull request, and delete any that are not.
If this PR introduces new functionality, include a user story or stories describing what this pull request is intended for.
1.  If the PR fixes a bug, include step-by-step instructions for reproducing the bug on a current DKAN release.
> Updating Add Content page and content types

- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.module
> file_resup 1.5 equals the revision being used

- modules/dkan/dkan_sitewide/dkan_sitewide.module
> Tidy up hook definitions

- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
- modules/dkan/dkan_datastore/src/Pages.php
> Restoring the API page.

- docs/admin/data_and_content/adding_new_content.rst
- docs/admin/people/group_roles_and_permissions.rst
- docs/components/dataset/groups.rst
Fixes #2629
Documentation updates related to #2630.
> Group roles & permissions documentation updates

- dkan.install
- modules/dkan/dkan_dataset/dkan_dataset.module
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.features.field_base.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.features.field_instance.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.module
- modules/dkan/dkan_harvest/dkan_harvest.module
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/css/dkan_harvest_dashboard.css
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/dkan_harvest_dashboard.module
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/dkan_harvest_dashboard.views_default.inc
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- modules/dkan/dkan_migrate_base/README.md
- modules/dkan/open_data_schema_map_dkan/open_data_schema_map_dkan.features.inc
- test/features/dkan_harvest.feature
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationTest.php
- themes/nuboot_radix/assets/css/nuboot_radix.style.css
- themes/nuboot_radix/scss/components/_harvest.scss
connects #2612
Removed the filter for modified 'Date', added a few others
> Add check for non-date modified values when harvesting

- drupal-org.make
> Updating ODSM to 2.1.

- drupal-org.make
- modules/dkan/dkan_environment/dkan_environment.info
- modules/dkan/dkan_environment/dkan_environment.module
> Adding a dkan_envrionment module which configures a useful basic set of environments.

- docs/components/datastore.rst
- modules/dkan/dkan_datastore/src/Page/Page.php
- test/features/resource.admin.feature
> First pass at the documentation for the new datastore.

- docs/admin/data_and_content/data_management.rst
- docs/components/datastore.rst
- modules/dkan/dkan_datastore/src/Page/Page.php
connects #2569 
Update documentation of new datastore and clean up redundant info in the admin section.
> Datastore docs updates

- drupal-org-core.make
Security update https://www.drupal.org/SA-CORE-2018-006
> Update drupal to 7.60

- dkan.install
making room for hooks on 7.x-1.x
> Re-number hook updates

- modules/dkan/open_data_schema_map_dkan/open_data_schema_map_dkan.features.inc
connects #2716 
1. Add a resource to a dataset using the **remote file** field
2. rebuild the data.json file `drush odsm-filecache data_json_1_1`
3. confirm the downloadURL is valid (url only, no html)
> Update odsm_dkan token values

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
> Fix postImportRestoredSource() function to be php7 compatible

- docs/apis/datastore-api.rst
> Temp doc adjustment until API is fixed

- docs/development/display-num-datasets.rst
- docs/development/index.rst
I created a quick recipe based on a request from slack.
> Number of Datasets and Topics Recipe

- modules/dkan/dkan_workflow/dkan_workflow.features.workbench_email.inc
- modules/dkan/dkan_workflow/dkan_workflow.info
connects GetDKAN/dkan/issues/2759
Improvements for text in workflow moderation state change emails.
> Issue GetDKAN/dkan#2759: workflow emails changes

- drupal-org.make
--------------
**Issues with these**
> Upgrade contrib modules to latest versions

- modules/dkan/dkan_dataset/dkan_dataset.module
connects #2688
1. Create a harvest source from https://api.myjson.com/bins/v2248
2. Confirm you get errors
> Add check for partial date elements when validating

- drupal-org.make
- RESTful Web Services - Critical - Access bypass - SA-CONTRIB-2019-018
- Link - Critical - Remote Code Execution - SA-CONTRIB-2019-020
> Security updates for link and restws

- drupal-org-core.make
> Upgrade drupal to 7.64

- modules/dkan/dkan_datastore/dkan_datastore.drush.inc
I committed this by accidental to ``7.x-1.x``. This reverts the change.
> Revert dkan_datastore.drush.inc

- drupal-org.make
Services: https://www.drupal.org/sa-contrib-2019-026
Path Breadcrumbs: https://www.drupal.org/sa-contrib-2019-027
> Update services and path_breadcrumbs modules

- drupal-org.make
- Views (security update)
- ctools
- features
> Contrib updates

- .circleci/config.yml
- test/features/dkan_harvest.feature
- test/features/theme.admin.feature
Connects GetDKAN/dkan-tools#14
> Fist attempt at running tests with dktl.

- docs/introduction/dkan-sites.rst
> Added DKAN site in Bolivia to list of DKAN sites.

- docs/admin/people/index.rst
- docs/apis/datastore-api.rst
- docs/components/datastore.rst
Connects https://github.com/NuCivic/dkan_management/issues/191
> Document new datastore behavior.

- docs/introduction/dkan-sites.rst
Confirm sites from #2861 have been added
> Add pacific islands data sites to the docs

- drupal-org.make
Applied security update for module UUID: https://www.drupal.org/sa-contrib-2019-052 
Applied security update for module tablefield: https://www.drupal.org/sa-contrib-2019-051
> Security update for uuid and tablefield

- drupal-org.make
Pull in [updates to ODSM](https://github.com/GetDKAN/open_data_schema_map/releases/tag/7.x-2.2)
> Update Open Data Schema Map to 7.x-2.2

- modules/dkan/dkan_datastore/src/LockableDrupalVariables.php
- modules/dkan/dkan_datastore/src/Locker.php
Moving the functions so we can add drush commands to trigger the locking and unlocking
> Move getLock() and removeLock() to a separate class

- docs/apis/datastore-api.rst
Updated Datastore API docs on how to filter and specify fields.
> Updated how to filter and specify fields on datastore api.

- drupal-org.make
Security update https://www.drupal.org/sa-contrib-2019-056
> Update imagecache actions to 1.10

- drupal-org.make
Update version of ODSM
see [ODSM #114](https://github.com/GetDKAN/open_data_schema_map/pull/114)
> Update ODSM to 2.3

- docs/introduction/dkan-sites.rst
Added Tirana Open Data portal to DKAN sites list.
> Added Tirana Open Data portal to DKAN sites list.

- docs/introduction/dkan-sites.rst
#2922 
Add site to docs/introduction/dkan-sites.rst
> Add dkan site to list of documented sites

- docs/development/feedback.rst
- docs/development/index.rst
- docs/requirements.txt
Needs to be reviewed by a developer; may also need to clean up formatting
> Created feedback.rst

- modules/dkan/dkan_fixtures/modules/dkan_default_content/data/files/resource/Polling_Places.csv
- modules/dkan/dkan_fixtures/modules/dkan_default_content/data/package_show%3Fid=wisconsin-polling-places.json
- modules/dkan/dkan_fixtures/modules/dkan_default_content/data/resource_show%3Fid=37971f0c-a5e8-4c0c-9dbc-d6fe5fb54607.json
- test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
- test/phpunit/phpunit.xml
Localize default content resource.
fixes https://github.com/NuCivic/dkan_management/issues/286
> Fix polling places file

- test/features/data_story.author.feature
- test/features/group.all.feature
Add identifiers to data_story.author tests. 
Remove @smoketest tag from group.all.
> Tests updates.

- drupal-org.make
Just fix a typo in drupal-org.make
> Fix branch/tag in drupal-org.make

- dkan.install
- drupal-org.make
- modules/dkan/dkan_sitewide/dkan_sitewide.info
- modules/dkan/dkan_sitewide/dkan_sitewide.views_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.features.menu_links.inc
- test/features/user.editor.feature
- themes/nuboot_radix/assets/css/nuboot_radix.style.css
- themes/nuboot_radix/scss/components/_view.scss
> Remove admin_views

- dkan.install
- dkan.profile
@dharizza one more when you get a chance.
> Remove admin_views from system table

- modules/dkan/dkan_sitewide/dkan_sitewide.module
- test/features/search.feature
Fixes: https://github.com/NuCivic/dkan_management/issues/329
> Remove 404 redirect

- CHANGELOG.txt
- drupal-org.make
https://www.drupal.org/node/3054091
Error: Call to a member function get_access_callback.
> Add views patch 3054091

- drupal-org.make
Security update: https://www.drupal.org/sa-contrib-2020-001
> Update radix to 3.8

- drupal-org.make
> Upgrade recline to 7.x-2.2

- README.md
Non-substantive change to the licensing statement.
> Fixing up the formatting of Licensing statement

- modules/dkan/dkan_datastore/src/Page/Page.php
> add fix from @dinhthimaianh
