- dkan.profile
Issue: https://github.com/NuCivic/nucivic-internal/issues/325
Note: The error messages were fixed in another commit. A flush of the image styles was added in order to make the image appear since in some cases a refresh was needed in order for the images to be shown.
> NuCivic/nucivic-internal#325 - Flushed image styles on install.

- modules/dkan/dkan_sitewide/dkan_sitewide.module
See: https://github.com/NuCivic/dkan/issues/382
> NuCivic/dkan#382 - Show notices only on available updates report.

- dkan.info
- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.facetapi_defaults.inc
>
> DO NOT GET THIS IN AS IT IS. THE CODE HERE IS ADAPTED TO BRING UP A 
> QA SITE TO EVALUATE CHANGES IN THREE DIFFERENT COMPONENTS (REPOSITORIES).
> 
#447
>
> DO NOT GET THIS IN AS IT IS. THE CODE HERE IS ADAPTED TO BRING UP A 
> QA SITE TO EVALUATE CHANGES IN THREE DIFFERENT COMPONENTS (REPOSITORIES).
>
> QA Only. Updates in license block and facet rendering

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.info
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
The panel content for 'Resource' content type was modified. A "node being viewed" block was added instead of "Node loaded from %1".
> NuCivic/dkan#436: Removed duplicated message.

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
Mapbox changed their example tile so the data extent map doesn't work. This fixes it.
> Fix Data Extent Map

- drupal-org-core.make
This updates to Drupal core version 7.39.
We should merge if tests pass.
> Update to 7.39

- drupal-org.make
Change in drupal-org.make to add a patch to restws and fix the drupal upgrade issue about specifying the resource format via URL.
> NuCivic/dkan#652: added patch in restws to fix resource format extensions.

- drupal-org.make
https://github.com/NuCivic/internal/issues/796
Original issue for Radix that has now been committed
https://www.drupal.org/node/2473455
I don't have a copy of the error you would get without the patch, but if you don't see any errors related to a bootstrap template, it is working
> use latest version of radix

- dkan.profile
> Disable og_extras_members on DKAN install

- dkan.info
- dkan.profile
- test/features/vis_entity_embeds.feature
This responds to the issue https://github.com/NuCivic/internal/issues/877
> NuCivic/internal#877: visualization embed

- drupal-org.make
This fixes the bug described here: https://github.com/NuCivic/internal/issues/878.
Every time the cron is executed, then the page styles are broken because of a file not found.
> Fixed problem with cron bug on colorizer

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
Pulled from USDA downstream. No particular ticket to reference.
Domain fixed:
* openstreetmap.org
* assets.okfn.org
Credits goes to @upieper.
> Use https for urls used in dataset view page

- drupal-org.make
The colorizer fix we introduce is throwing some warnings during the installation process. I've reviewed how the colorizer fix works and I've created another patch following the colorizer creator suggestions.
Acceptance test
---------------------
Drupal thread is here https://www.drupal.org/node/2599298#comment-10654038
> Fix colorizer fix throwing errors during installation process

- drupal-org.make
This removes an annoying warning in some drupal forms. 
Acceptance test
-----------------------
> Add patch to remove radix warning in forms

- .probo.yml
Enables QA site builds.
Ref: NuCivic/pluto#116.
> Enable proboci QA site builds.

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
The dkan groups view is a 3 column display, displaying 10 items on a page leaves one orphaned group on the last row by itself.
> Update dkan_groups view to display 12 items per page rather than 10

- .probo.yml
As a QAer I don't want to have to look up the password of a QA site.
Acceptance:
==========
> Make probo admin password admin.

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.module
1. Go to /dataset
2. Use a bunch of facets aside from "Type"
3. They should stay open once the page reloads, and dissapear if disabled.
> Make facets expanded if in use on search page

- circle.yml
`circle.yml` was pointing to an old file that doesn't exist anymore.
> Fix data_story feature reference in circle.yml

- .ahoy/docker-compose.yml
- circle.yml
from 2.48.2 to 2.50.0 in the hope that chrome will stop crashing.
> CIVIC-906 Update the circleCI and docker selenium versions

- .ahoy/docker-compose.yml
- circle.yml
- There is a known 2.50.0 timeout issue, that was just fixed in 2.50.1, but no docker image just yet. See https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG
- Remove the shutup of selenium, so at least we might be able to debug things better in the future.
> Downgrade selenium to 2.49.1 from 2.50.0

- .ahoy/docker.ahoy.yml
Getting docker-compose output while `ahoy dkan mysql-dump`
```
2016/02/08 12:29:42 ===> AHOY mysql-dump from  : docker exec -it $(docker-compose -f  ps -q cli) bash -c 'mysqldump -u$DB_ENV_MYSQL_USER -p$DB_ENV_MYSQL_PASSWORD -h$DB_PORT_3306_TCP_ADDR $DB_ENV_MYSQL_DATABASE'
Define and run multi-container applications with Docker.
Usage:
docker-compose [options] [COMMAND] [ARGS...]
docker-compose -h|--help
Options:
-f, --file FILE           Specify an alternate compose file (default: docker-compose.yml)
-p, --project-name NAME   Specify an alternate project name (default: directory name)
--verbose                 Show more output
-v, --version             Print version and exit
Commands:
build              Build or rebuild services
help               Get help on a command
kill …
```
> Missing ahoy for ahoy dkan mysql-dump command

- .ahoy/site.ahoy.yml
As a site developer I want to take advantage of Acquia deployment scripts in my QA build and testing processing.  This change adds an alias to the docker instance if available so that calls to drush @local or whatever works.
Acceptance
==========
This will help in cases where we are taking advantage of a deployment script
that requires an alias passes to it.
> Copy drush alias.

- .ahoy/.mysqlscripts/sanitize.sql
- .ahoy/site.ahoy.yml
Issue #CIVIC-940
```
ahoy site mysql-dump-sanitized
```
+ Creates `backup/unsanitized.sql` file from working db
+ Creates a `backup/sanitized.sql` file out of the working db after running `dkan/.ahoy/.mysqlscripts/sanitize.sql`.
+ Restores `backup/unsanitized.sql`
> Ahoy command to create a sanitized db out of the working docker db

- test/circle-behat.sh
In order to override some behat params we need to allow circle_behat.sh to 
receive behat parameter and pass them to the ahoy test function. In this way
each project can specify things like tags to exclude or include.
> Allow pass extra params to ahoy tests proxied through circle_behat

- .ahoy/site.ahoy.yml
Ref civic-1396
Acceptance:
==========
> Fix ahoy site mysql-dump-sanitize.

- .ahoy/site.ahoy.yml
Ref. civic-1394
Adds some ahoy site api commands to work with s3 asset buckets.
None of this is written in stone yet.  But we can decide on the api format now.
Note that most of this is just templates as implementation is still foggy and
depends on further decision making.
Acceptance:
==========
should download db from s3 bucket.
> Add ahoy command to download db files from s3 bucket.

- test/composer.lock
Adds support for maillog being enabled during mail tests.
> Update dkanextension to the latest version: 

- .ahoy/site.ahoy.yml
Issue #CIVIC-1405:
+ Grabs gunzip version of sanitised db to save bandwith
+ Fixes wget output for asset-download-files (was outputting to sanitised.sql)
> ahoy site asset-download-db to grab gunzip sanitised db

- .ahoy/.scripts/site-name.php
- .ahoy/site.ahoy.yml
Ref Civic-1416.
Getting name using drush sa was not working now getting it directly from aliases array.
Also the db name changed.
Acceptance
=========
> Fix db download.

- test/composer.json
- test/composer.lock
The dev branch on Behat is now based on 3.1. Pointing to 3.0 was causing Behat to be downgraded to an old stable 3.0 version which was causing the tests to fail due to 'junit' not available:
NOTE: After the upgrade to 3.1 was done some changes were required on dkanextension in order to make services.yml to be valid YML. A PR was created here in order to fix that: https://github.com/NuCivic/dkanextension/pull/30. The dkanextension branch must be restored before merging this PR.
> Behat upgrade to 3.1

- circle.yml
Temporary fix for drush bin's not being setup on circle.ci
> Prepends circle io composer global bin to PATH

- .ahoy/dkan.ahoy.yml
This command is a complement of `ahoy site self-update`.  It's a way to conviniently update the ahoy specific components to the latest 7.x-1.x verision of dkan.
The use case is for site remakes to capture latest version of ahoy while not needing to upgrade all of dkan.
Ref civic-1506
Acceptance
=========
> Add `ahoy dkan self-update` command.

- drupal-org.make
This PR was created based on: https://github.com/NuCivic/dkan/pull/838
Ref: https://jira.govdelivery.com/browse/CIVIC-512
1. Go to 'admin/appearance/fontyourface/browse/google_fonts_api'.
2. Enable a font, any font.
3. Go to "Enabled fonts" tab.
4. Choose "Everything (Body)" from the font CSS selector dropdown list.
5. Save.
6. Go to "Browse Fonts" tab and disable the font.
7. Reload the page, drupal default font should be used on the page.
> Added patch on fontyourface to fix bug when fonts are disabled.

- .ahoy/dkan.ahoy.yml
Ref civic-1510.
`ahoy dkan test` requires that the behat.docker.yml and behat.circleci.yml be
present.  But, current sites do not include these files.  If we add these file
during an `ahoy dkan self-update` Then there is always a simple and automatic
way to keep these files present and current in any of the data_starter type
projects.
Acceptance
==========
the docker and circleci behat config files which are required in order to run
`ahoy dkan test` from within a site project.
> Add docker and circle behat config files on update.

- drupal-org.make
- test/features/resource.all.feature
Tests for #944 
If they pass, merge NuCivic/nuboot_radix#70, then point drupal-org.make back to nuboot_radix 7.x-1.x before merging.
> 944 resource teaser

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
Issue: https://github.com/NuCivic/dkan/issues/1018
Facet titles are not standardized
- As a site user I want to see consistent titles on facets so it is clear they are the same filters across various search pages.
> Update facet block titles on group and user pages

- CHANGELOG.txt
- modules/dkan/dkan_featured_topics/dkan_featured_topics.info
Issue: None
The variable 'taxonomy_menu_vocab_parent_dkan_topics' was present on the .info and since its not being exported it was causing the 'Topics' feature to be marked as Overriden.
None.
> Removed unused variable from topics info file.

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.install
Issue: None.
A hook_update() function was added on dkan_sitewide_menu in order to remove the 'Add Dataset' and 'Datasets' link. The new 'Datasets' link is added by the dkan_sitewide_search_db feature and it points now to the search page instead of '/dataset'.
Here is a dump of a clean 7.x-1.11 install:
[7-x-1-11.sql.zip](https://github.com/NuCivic/dkan/files/200287/7-x-1-11.sql.zip)
> Added hook_update to update menu items on main menu.

- modules/dkan/dkan_featured_topics/dkan_featured_topics.module
Issues: https://github.com/NuCivic/dkan/issues/1062
Data.json validation was failing because of the 'downloadURL' field not being a full path. 
None.
> Fixed regex used to rewrite font file paths on Dkan Topics.

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_menu/dkan_sitewide_menu.features.menu_links.inc
When logged in as an editor or site manager, the admin menu link for adding a data story is incorrect.
> Fix typo in add data story link

- .ahoy/dkan.ahoy.yml
This attemps to allow module linking for other modules other than the ones located at `dkan/modules/dkan`
> Smarter module-link ahoy dkan command

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
https://github.com/NuCivic/dkan/issues/951
file sizes are displayed as just a string of numbers, lets format those to be easier to 'read'
> GH-951 add formating to filesize display

- .ahoy/docker.ahoy.yml
Ref CIVIC-2483.
Acceptance
=========
> Allow users to run `ahoy docker exec` in all cases.

- modules/dkan/dkan_data_dashboard/dkan_data_dashboard.info
Just want to remove the word "Sitewide" from the module name for consistency.
> Remove "Sitewide" from DKAN Data Dashboard module name

- drupal-org.make
- modules/dkan/dkan_topics/dkan_topics.module
Issue: civic 2580
https://github.com/NuCivic/dkan/issues/1088
508 fail: Front Page
Topics view contains empty links (icons)
https://github.com/NuCivic/nuboot_radix/pull/85
Update drupal-org.make file to reset the nuboot_radix branch back to 7.x-1.x before merge.
> Add text to icon links for 508 compliance

- .ahoy/dkan.ahoy.yml
- .ahoy/docker-compose.yml
- .ahoy/docker.ahoy.yml
Ref CIVIC-2392
The new container adds does not have xdebug configured. Some new helper
commands have been added.
`ahoy docker apache start|stop|restart`
`ahoy docker xdebug start|stop`
`ahoy docker log (access|error)`
Acceptance
=========
> Use nuams/web container.

- .ahoy/dkan.ahoy.yml
- .ahoy/docker.ahoy.yml
Ref CIVIC-2593 CIVIC-2483 CIVIC-2392
This implementation also fixes `ahoy dkan reinstall` which broke when the new `ahoy docker exec` was implemented.
Accetance
========
> Allow `ahoy docker exec` on all containers.

- .ahoy/docker-compose.yml
The nuams/drupal-cli container now has `drush rr` out of the box.
Ref Civi-2385
Acceptance
==========
> Use nuams/drupal-cli container.

- .ahoy/dkan.ahoy.yml
Ref CIVIC-2718
`ahoy dkan test` is failling locally do to ahoy exec/cmd-proxy requiring a new abstraction step.  Some characters now require to be escaped in order to work properly.
AC
==
> Fix ahoy dkan test command.

- .ahoy/dkan.ahoy.yml
- .ahoy/starter.ahoy.yml
- .ahoy/utils.ahoy.yml
There may be an issue with DB backup not getting created on `ahoy dkan reinstall`.
However, this is likely an underlying issue with `ahoy compare` not able to
handle the default behavior without throwing an error.
This commit fixes that issue and by proxy the other issue.
Ref civic-2918
AC
==
> Fix `ahoy compare` default not working.

- modules/dkan/dkan_permissions/dkan_permissions.features.roles_permissions.inc
Brings in editor permissions for ECK, solving problem of editors not being able to use viz entity admin menu items.
> Viz perms release

- .ahoy/dkan.ahoy.yml
Ref CIVIC-2958
Adds `ahoy dkan uli` to mimic `drush uli` in our docker environment.
AC
==
> Add `ahoy dkan uli` command

- test/features/recline.feature
The recline test started failing after the wait 3 seconds was removed, so adding it back.
> fix recline test

- CHANGELOG.txt
- dkan.info
- dkan.profile
- drupal-org.make
- modules/dkan/dkan_permissions/dkan_permissions.features.roles_permissions.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.features.filter.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.info
- test/features/user.admin.feature
issue: civic 2811
https://github.com/NuCivic/dkan/issues/1180
As a Site Manager creating a new user, I am not allowed to set the user's role in DKAN 7.x-1.12.
Adds workflow roles to the available roles for site admins to assign users to
https://github.com/NuCivic/dkan_workflow/pull/45
> Add roleassign module, update permissions, add tests

- test/features/dataset.all.feature
This fixes some of the failing dataset search scenarios by adding wait instructions.
> Adding wait to dataset search to get tests passing

- test/features/markdown_editor.feature
Dkan markdown_editor tests fail because some of the shortcuts changed.
It is possible to run the same test steps without explicitly stating the shortcuts.
This PR removes the shortcuts from the testing steps.
> Removing markdown shortcuts from test steps.

- test/features/group.all.feature
Groups on homepage is customizable. This should be reflected in the tests with a ``@customizable`` flag.
> Tests reflect that groups on homepage is customizable

- test/features/dataset.author.feature
REF CIVIC-3578
The tags are not available at time of testing and causing test to fail.  Also we
need to change tags to be less likely to collide.
AC
==
> Fix tag collision when testing sites.

- drupal-org.make
- themes/dkan/templates/node--dataset.tpl.php
- themes/dkan/templates/node--group.tpl.php
- themes/dkan/templates/node--resource.tpl.php
- themes/dkan/templates/node.tpl.php
- themes/dkan/templates/region--branding.tpl.php
Issue: https://jira.govdelivery.com/browse/CIVIC-3647 https://github.com/NuCivic/dkan/issues/1225
If we are using a folder with the host for example hostname/dkan we are gettings some problems with links in some pages because we are using / instead to use relative paths. 
…-3647
> Fix views relative apth civic 3648

- modules/dkan/dkan_topics/dkan_topics.module
- test/behat.yml
- test/features/search.feature
Issue: CIVIC-3773
Topics broke with the XSS fix. This restores the topics page.
> Fix topics page

- test/features/data_story.author.feature
- test/features/dataset.all.feature
- test/features/widgets.feature
Test updates:
- The "Stories" menu item is customizable so should be noted as so in the tests.
- Widget tests expects that ``Afghanistan Elections District``  be one of the top 3 datasets alphabetically but that is not the case in some clients.
- Adds wait for facet to show up in Dataset search
> Data Story Menu Item Test Should be Customizable

- CHANGELOG.txt
- drupal-org.make
- test/features/data_story.author.feature
- test/features/dataset.all.feature
- test/features/widgets.feature
The following patch is necessary for some sites to upgrade properly: https://www.drupal.org/node/2762351
This adds the following to the ``panaleizer_update_7300()`` function:
```
// Bail if no records found.
if (empty($sandbox['max'])) {
return t('No records need to be fixed.');
}
```
Which produces volumes of ``Division by zero panelizer.install:1203 [warning]``. Following the warnings the update functions run which may cause the updates to fail.
> Panelizer patch 

- dkan.profile
civic 1748
The Dataset's Data Dictionary field does not filter using HTML. The instructions that appear for the Data Dictionary field suggest creating a table, "This usually consists of a table." Having that instruction in a field where it is impossible to add a table is a bug.
The field remains a textarea field but is reduced to a single line, expandable if needed.
https://github.com/NuCivic/dkan_dataset/pull/258
> QA - Update data dictionary field to use filtered html

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.views_default.inc
The search page and dataset pages invite the user to modify these pages with the IPE buttons, and we do not want users changing these particular pages.
> Remove ipe from dataset and search pages

- CHANGELOG.txt
- modules/dkan/dkan_fixtures/includes/dataset.inc
Issue: https://jira.govdelivery.com/browse/CIVIC-3833
Two warnings were displayed during install because of the override on field mapping.
- As a user I should not see any warnings during DKAN installation.
> Removed field mapping warnings on dkan_default_content

- CHANGELOG.txt
- dkan.install
- dkan.profile
Issue: CIVIC-3117
- Acunetics scan (see epic CIVIC-3063) identified a vulnerability in jquery 1.8
- jquery 1.9 breaks recline previews
- jquery 1.10 fixes both issues: this PR updates the default library setting on install and includes a hook update to run on current builds.
> Update jquery to 1.10

- .ahoy/.scripts/dkan-test.rb
REF CIVIC-4103
A recent change that uses ruby instead of bash to run circle scripts is not
exiting properly on errors.  This is causing some false positive to get through
that needs to be correct ASAP.
This change fixes the underlying cause of the issue.
QA Steps
===
```
set -e
echo "Hello"
ruby dkan/.ahoy/.scripts/circle-behat.rb dkan/test/features/myfailure.feature
echo "World"
```
> Fix ruby script not exiting properly.

- modules/dkan/open_data_schema_map_dkan/open_data_schema_map_dkan.features.inc
Issue: civic-4101
The data.json validation is failing because of errors on the '@type' property.
**This is where the change happened**
https://github.com/NuCivic/open_data_schema_map_dkan/commit/0b6fc89bf1e5bb836ff70012cb682fae7ca3b305
> Fix odsm validation

- dkan.profile
dkan.profile breaks on PHP <5.4 because of [] array assignment syntax. We should avoid breaking PHP 5.3 compatibility when possible. All this should need is for tests to pass.
> Remove PHP > 5.3 assignment syntax from dkan.profile #1372

- CHANGELOG.txt
- drupal-org.make
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_search_db/dkan_sitewide_search_db.security.inc
- modules/dkan/dkan_topics/dkan_topics.entity_path.inc
- modules/dkan/dkan_topics/dkan_topics.features.field_base.inc
- modules/dkan/dkan_topics/dkan_topics.features.field_instance.inc
- modules/dkan/dkan_topics/dkan_topics.module
- test/features/topics.feature
Issue: civic-4008, civic-4068
Using an & or / in a Topic name shouldn't cause the icon to disappear.
https://github.com/NuCivic/nuboot_radix/pull/97
> Fix topics menu to work with special characters

- circle.yml
- modules/dkan/dkan_topics/dkan_topics.make
* Update the php version in circle.
New images in CircleCi are not supporting PHP version 5.5.11 by default.  PHP 5.5.21 is the currently highest supported in newer Ubuntu 12.04 images.
REF CIVIC-4224
* Update php version to 5.6.14
REF civic-4224
running out of memory when trying version 5.5.21
* Update circle.yml
* Update circle.yml
* Update circle.yml
* Update circle.yml
* Use mysql-version 5.6
* Update circle.yml
* Update dkan_topics.make
* Update dkan_topics.make
> Support mysql 5.7 (#1379)

- drupal-org.make
Issue: https://jira.govdelivery.com/browse/CIVIC-4099
Warnings displayed on status page: (admin/reports/status)
imgAreaSelect Not installed
The Spyc library could not be found.
> Missing spyc library civic 4099

- .ahoy/docker-compose.yml
Issue: https://jira.govdelivery.com/browse/CIVIC-4369
Pin cli image to a tag instead of latest. The idea is to control the upgrade process to ahoy v2 without breaking developers environments.
> Pin cli image to tag.

- drupal-org.make
- modules/dkan/dkan_data_dashboard/dkan_data_dashboard.features.field_instance.inc
- modules/dkan/dkan_data_story/dkan_data_story.features.field_instance.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.features.field_instance.inc
- modules/dkan/dkan_topics/dkan_topics.features.field_instance.inc
Issue:https://jira.govdelivery.com/browse/CIVIC-4093
The default view modes of panelized content types should have all fields marked as hidden.
> Hidden fields view modes panelizer 4093

- .ahoy/docker-compose.yml
Issue: https://jira.govdelivery.com/browse/CIVIC-4369
Downstream integration of REF #1415
Description
====
Pin cli image to a tag instead of latest. The idea is to control the upgrade
process to ahoy v2 without breaking developers environments.
> Pin cli image to tag. (#1415)

- .ahoy/dkan.ahoy.yml
- .ahoy/docker.ahoy.yml
If you are using docker, this helps with the construction for the `mysql://` uri
As a developer, i need a quick way to set up the drupal database settings within the docker environment.
> Helper to build docker mysql url

- .ahoy/dkan.ahoy.yml
#1219 broke the ahoy build commands. This should fix it.
> Update dkan.ahoy.yml to stop deleting consolidated modules

- .ahoy/.scripts/behat-parse-params.rb
Behat two dashed flags should go at end.
> Fix too many arguments when running behat tests

- .ahoy/.scripts/dkan-make.sh
- .ahoy/.scripts/dkan-si.sh
- .ahoy/.scripts/drupal-rebuild.sh
- .ahoy/dkan.ahoy.yml
Some ahoy commands require a lot of escaping in order to work.  Unfortunately this voodoo magic is known to fail in some cases.  By moving these portions out we avoid errors that happen because the escaping acts differently in the local environment than in CI or Probo environment
> Move dkan make and build ahoy to scripts.

- circle.yml
Description
===
The PHP memory limit was recently updated as a timeout measure but this is not
required at this point.  This PR reverts that change.
> Reset php memory back to 256.

- CHANGELOG.txt
- modules/dkan/dkan_workflow/modules/views_dkan_workflow_tree/views_dkan_workflow_tree.module
Issue: civic-4410
Workbench legend variables display on harvest VBO forms due to small glitch in the views_dkan_workflow_tree_views_bulk_operations_form_alter function.
0. Enable dkan_workflow and dkan_harvest.
1. Create Harvest Source.
2. Harvest The source.
3. Go to "Manage Datasets" page.
4. Confirm the legend vars are displayed at the bottom of the form
No glitches at the bottom of the "Manage Datasets" page.
0. Enable dkan_workflow and dkan_harvest.
1. Create Harvest Source.
2. Harvest The source.
3. Go to "Manage Datasets" page.
4. Confirm there are no legend vars displayed at the bottom of the form
> Move legend code inside check for workbench form ID

- modules/dkan/dkan_harvest/dkan_harvest.path_breadcrumbs.inc
- [] Create a harvest source
- [] Go to the harvest source page
- [] Harvest Source link in the breacrumb should point to admin/dkan/harvest/dashboard
> Fix Harvest Source breacrumb path

- modules/dkan/dkan_harvest/dkan_harvest.pages.inc
Issue: [CIVIC-4496](https://jira.govdelivery.com/browse/CIVIC-4496)
The date issue only affects the last event table (top table).
1. Create Harvest Source {{Test}}. This source should have bag records that will generate harvest errors.
2.  Harvest {{Test}}.
3. Open **Errors** tab.
4. The top table header should have the correct errors count but the date should be wrong.
1. The date should be correct.
1. Update the Behat tests to include a check for the date.
N/A
> Harvest "Errors" first event table have wrong date in the header

- CHANGELOG.txt
- modules/dkan/dkan_harvest/dkan_harvest.module
Issue: https://jira.govdelivery.com/browse/CIVIC-4447
An "Notice: Undefined index: und" is being displayed when a resource is being edited.
1. Go to node/add/resource and create a resource. Do not assign a dataset.
2.- No errors will be displayed.
3.- On the resource page click 'Edit'
4.- A "Notice: Undefined index: und" warning will be displayed..
> Warning message edit resource without dataset civic 4447

- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/dkan-test.rb
Description
===
The parameter --no-colors is not being handled properly by our parameter parser because it's misspelled. Fixing the typo will fix this issue.
QA Steps
===
> Couple fixes for DKAN test default params and run directory

- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/dkan-test.rb
Description
===
The parameter `--no-colors` is not being handled properly by our parameter parser because it's misspelled.   Fixing the typo will fix this issue.
QA Steps
===
> Fix behat --no-colors broken.

- CHANGELOG.txt
- modules/dkan/dkan_harvest/dkan_harvest.module
Issue: https://jira.govdelivery.com/browse/CIVIC-4503
When a dataset is deleted the associated row on the harvest migration map table needs to be deleted as well in order to re-create the dataset when the source is harvested again.
> Removed row from migration map table when a dataset is deleted

- drupal-org.make
If workbench moderation patches correctly and the build completes, we're good
> Fix build problem due to workbench moderation download

- CHANGELOG.txt
- modules/dkan/dkan_dataset/dkan_dataset.theme.inc
Button text for the dataset download all link is displaying html
Confirm that the 'Download All' button on dataset pages show an icon and not the html for the icon.
> Fix dataset download all link

- modules/dkan/dkan_harvest/dkan_harvest.pages.inc
Issue: civic-4927
Undefined variable breaks Events table
1.  create a harvest source
2. visit the Events tab under the source page
> Restore harvest status set up CIVIC-4927

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.module
Issue: CIVIC-4771
The *Format* search facet does not display selected terms as expected, the block keeps the 'ctools-toggle-collapsed' class which hides the active content
1. Go to the search page
2. Select a Format term
3. Format facet item should not be collapsed (see screenshot).
> Fix Format search facet does not display selected terms

- .ahoy/.scripts/behat-parse-params.rb
Issue: -
Restore missing behat test fixes.
The fix was introduced in #1452 but reverted (probably by mistake).
Running behat test command with the `--no-colors` command will throw `Too many arguments.` exception. 
Running `ahoy dkan test --no-colors` should run the behat tests without throwing exceptions.
Backport for release 1.12: https://github.com/NuCivic/dkan/pull/1571
> Restore ahoy behat test command fixes

- CHANGELOG.txt
- modules/dkan/dkan_dataset/dkan_dataset.module
- test/features/dataset.author.feature
- test/features/resource.all.feature
- test/features/resource.author.feature
Issue: CIVIC-4448
When the "Back to dataset" button is clicked on a resource with no associated dataset the URL changes to /node/XXX/dataset and the view looks empty.
* Create a resource without associated dataset.
* Go to the view page.
* Click on "Back to dataset".
* The URL will change and the view will be empty (only the buttons will be displayed).
- "Back to dataste" button should not be available for resources without datasets.
> Hide "Back to dataset" button for datasetless resources [CIVIC-4448]

- CHANGELOG.txt
- drupal-org.make
There is a ton of fixed to include in dkan from vis entity. This PR creates points to the beta2 version of viz entity instead of beta1.
> Update viz entity chart version

- CHANGELOG.txt
- drupal-org.make
Issue: civic-4947
https://github.com/NuCivic/dkan/issues/1560
If running the site with clean urls disabled, the link for the dataset count button on group teasers will not work.
1. Disable clean urls
2. Go to the 'Groups' page
3. Click the blue dataset count button on one of the groups
4. Confirm that you do not get a Page not found error, you see the group node
https://github.com/NuCivic/nuboot_radix/pull/101
Restore **drupal-org.make** file when done with QA
> Update changelog with fix for group teaser links CIVIC-4947 (release)

- .ahoy/theme.ahoy.yml
Issue: CIVIC-4409
The ahoy command for creating a subtheme was not working
```ahoy dkan theme new-from-kit [theme name]```
1. set up local build
2. run the command above (use a one word theme name or use an underscore)
3. confirm that the new subtheme was created and is enabled as the default theme
> Fix subtheme creation command on release branch CIVIC-4409

- CHANGELOG.txt
- modules/dkan/dkan_datastore/dkan_datastore.module
- themes/nuboot_radix/includes/menu.inc
Issue: CIVIC-5020
Harvest source nodes display a 'manage datastore' button that should not be there
> Remove the manage datastore button from the harvest preview page. CIVIC-5020

- CHANGELOG.txt
- modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.module
- modules/dkan/dkan_datastore/dkan_datastore.module
- modules/dkan/dkan_datastore/includes/DkanDatastore.inc
This fixes a couple of bugs with running the datastore via cron.
The ``dkan_datastore_queue_import_worker()`` was calling a method ``updateByFile()`` that copied the file attached to the resource even if it already existed. The method was also being passed the ``$url`` instead of the ``$uri`` which meant that once cron was run the actual file was replaced with a URL.
I broke up the ``updateByFile()`` method to ``updateByFileURI()``, ``updateFile()``, and ``updateByCLI()``.
``dkan_datastore_queue_import_worker()`` now just calls ``updateByCLI()`` since the cron job has no reason to care about the file being attached. If files need to be attached then they can use the ``updateFile()` or ``updateByFileURI()`` methods. 
1. Tests wouldn't pass on DKAN Starter or locally. 
2. Running …
> Updates datastore cron workflow

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/dkan_sitewide.features.field_instance.inc
Accidental change to page body field to hidden on the release branch causes page content to 'disappear', the page content type is not panelized until 1.13
https://github.com/NuCivic/dkan/pull/1413
> Fix hidden page body field

- modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php
When we create a resource using a remote file we are getting:
```
Notice: Undefined index: Location in /Users/aaron/docker-share/dkan/dkan/modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php on line 210
string(59) "Hospital_Inpatient_Discharges_by_DRG__Northwest__FY2011.csv"
```
> Fix location warning when creating a remote resource

- test/features/topics.feature
REF https://jira.govdelivery.com/browse/CIVIC-4703
Description
===
The current behat scenario "Scenario: See topics on the homepage as anonymous
user" is testing a mute test becuase it checks for an icon that is already added
by the dkan profile on installation.  The problem is that on older sites that do
not run the profile, the default icon is not added revealing a test bug when
this icon is checked for.  Although the test adds the icon a background step, it
fails to correctly add the icon font and icon type because the table field are
not correctly mapped or the correct table field name is not used.
This commit fixes two issues.
front page, that way if there is an uderlying issue it is caught but the
upstream tests.
Steps to reproduce:
===
* On an OOB site remove the term topic term …
> Use correct term table fields.

- modules/dkan/dkan_dataset/includes/getRemoteFileInfo.php
- test/phpunit/dkan_dataset/getRemoteFileInfoTest.php
Issue: CIVIC-5112
This was reported by @marciuz afteris facing issue when harvesting xls resources with `application/vnd.ms-excel` mimetype with the following error:
{code:none}
Resource remote url ([Redacted])   [error]
extension (xlb) not allowed
{code}
The remote file mimetype is {{application/vnd.ms-excel}}, which can have mulitple extensions pre the default Drupal mimetype library {{xlb}}, {{xlt}}, and {{xls}}. Faced with this choice the Harvest will return the first extension {{xlb}} as the detected extension which is not part of the allowed extension list and will generate the error.
1. Using a data.json, set a resource url to xls file with 
2. Harvest the source.
*Expected*: The harvest should pass with no error. The harvested dataset should have a resource with the …
> [CIVIC-5112] Extension detection mismatch lead to error during Harvest

- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/views/handlers/views_handler_field_boolean_harvest_status.inc
Issue: https://jira.govdelivery.com/browse/CIVIC-4922
When you execute a harvest migration and fail the first time if you try to execute again the status on dashboard is ok.
1.  Create a harvest node with https://raw.githubusercontent.com/NuCivic/dkan/7.x-1.x/test/phpunit/dkan_harvest/data/dkan_harvest_datajson_test_error.json you should see on dashboard status ERROR.
2.- Execute again and you will see OK on status field.
> Fix: Error status is lost when harvest run for a second time

- CHANGELOG.txt
- modules/dkan/dkan_workflow/dkan_workflow.install
Issue: CIVIC-5111
After enable dkan workflow we have missing menu links to workbench. 
1.  Enable dkan workflow. And then you can't see any link on the top.
> Revert menu links for workbench after enabling DKAN workflow

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_dashboard/views/handlers/views_handler_field_boolean_harvest_status.inc
- modules/dkan/open_data_schema_map_dkan/open_data_schema_map_dkan.features.inc
Issue: CIVIC-5125
data.json displays $base_url (default when no group present) rather than the publisher name due to a bad token.
See: https://github.com/NuCivic/open_data_schema_map_dkan/pull/18
Not sure why we needed to limit to a single publisher but if so then we may need to create a custom token...?
1. view http://demo.getdkan.com/data.json
2. notice the datasets that do have groups still display default publisher values >> `publisher":{"@type":"org:Organization","name":"demo.getdkan.com"}`
Same fix on the original repo for fixing 7.x-1.12.x sites
https://github.com/NuCivic/open_data_schema_map_dkan/pull/24
> Fix publisher token so data.json displays group title CIVIC-5125

- CHANGELOG.txt
- modules/dkan/dkan_harvest/README.md
- modules/dkan/dkan_harvest/dkan_harvest.drush.inc
- modules/dkan/dkan_harvest/dkan_harvest.info
- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
- modules/dkan/dkan_harvest/includes/HarvestMigrateSQLMap.php
- modules/dkan/dkan_harvest/includes/HarvestMigrateSourceList.php
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationTest.php
Issue: CIVIC-5160
This will make the Harvest Migration support the '--limit' option as provided by the base migrate class/module.
Also this improve support for the '--instruments' option to provide basic performances monitoring for the harvest cache and migrate steps.
This PR include some bug fixes for the drush commands provided by `dkan_harvest` (including '--skiphash' option).
1.  Create a Harvest Source node (named Test) with data.json test endpoint.
2. Test updated `--skiphash` option:
i. Do a first harvest (either from drush or the GUI).
ii. Running the harvest from drush with the '--skiphash' option should disable source diff check and re-harvest and update every dataset previously harvested.
3. Test added `--limit` option:
i. Running a harvest from drush should only harvest the …
> [CIVIC-5160] Support 'limit' migration option in HarvestMigration

- CHANGELOG.txt
- drupal-org.make
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANContext.php
- test/features/resource.author.feature
Issue: CIVIC-3687
Currently validation is not complete on the resource file fields. 
1.  Add a new resource: `node/add/resource`
2. Fill in both the **Remote file** and the **API or Website URL** fields
3. Enter a title
4. Save - confirm you see errors about adding more than one resource type
> Add test for using too many resource types CIVIC-3687

- CHANGELOG.txt
- drupal-org.make
- test/features/dkan_harvest.feature
Issue: Civic 4866
DOM-based cross-site scripting arises when a script writes controllable data into the HTML document in an unsafe way. 
1. Log in and open a dataset form
2. Confirm the field_group fields function properly (ie click on "Upload", "API")
> Add patch to field_group to avoid DOM-based cross-site scripting Civic 4866 (DEV)

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
- test/features/workflow.feature
Issue: CIVIC-5348
The *View draft* tab on moderated datasets (ie dkan_workflow enabled) is not working correctly and displays the published dataset node in place of the expected draft.
This is due to the pane used by the `node_view` panel page is discarting the current node revision and only using the node id to render the node.
1. Enable `dkan_workflow` module.
2. From a node that already have a published revision. Create a new draft revision.
3. Click on the *View draft* tab. (Or use node/%nid/draft).
*Expected*:
1. The updated content is shown.
*Actual*
1. The published node revision is displayed.
This behavior is not affecting the node edit page.
> [CIVIC-5348] "node/%nid/draft" and "node/%nid/revision" link does not show the corrcet node revision 

- dkan.install
- test/features/dataset.author.feature
- test/features/dataset.editor.feature
- test/features/resource.admin.feature
- test/features/resource.all.feature
- test/features/search.feature
- test/features/theme.admin.feature
Issue: CIVIC-5434
We need tests to pass on both DKAN OOB and client sites. 
1. **theme.admin.feature**
Since client sites may have custom hero images, add the @customizable tag to Scenario: Add custom hero image
2. **dataset.author.feature** / **dataset.editor.feature**
Client sites (cadepttech) may not have the 'zip' format in their list of terms, remove the format column in backgrounds where it is not needed and simplify with more common formats when it is
3. **resource.admin.feature** / **resource.all.feature**
Only one test on resource.all.feature requires a csv format
4. **search.feature**
See number of datasets on search page (change test to use a search term no client site would be using)
> Update tests to account for client site variations CIVIC-5434

- drupal-org.make
This addresses DKAN security alert [DRUPAL-SA-CONTRIB-2017-003 ](https://www.drupal.org/node/2842730) on the dev (1.13) branch
* Autocomplete deluxe field (the keywords in dataset) behaves as normal
* WAVE 508 tests still pass on dataset form
> Upgrade autocomplete_deluxe to fix security vulnerability

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/dkan_sitewide.module
Issue: https://jira.govdelivery.com/browse/CIVIC-4887
The upgrade script fails on a conversion step for some sites depending on whether a page is already the frontpage; so here we add a function to check that.
> CIVIC-4887: Added a function to check if a page is the frontpage.

- CHANGELOG.txt
- drupal-org-core.make
Issue: https://jira.govdelivery.com/browse/CIVIC-5507
dev PR #1688 
The drupal 7.50 -> 7.51 introduced conflicts between drupal core tabledrag's functionality and newer jquery versions set via jquery_update.
> Updates to drupal 7.53

- CHANGELOG.txt
- drupal-org.make
Issue: CIVIC-4889
workbench_moderation_states_features_rebuild() and workbench_moderation_transitions_features_rebuild() call features_get_default() and pass the result directly to a foreach. However, features_get_default() can return boolean FALSE instead of an array, causing the following notice:
**Invalid argument supplied for foreach() in workbench_moderation.features.inc**
1. Enable dkan_workflow
2. Disable dkan_workflow and workbench_moderation
3. Enable dkan_workflow, notice the error
> Add patch for workbench_moderation  CIVIC-4889

- test/dkanextension/src/Drupal/DKANExtension/Context/WorkflowContext.php
This fix issues we were experiencing in some client sites with workflow tests. Workflow was not "cleaning up" after itself correctly, modules need to be more properly enabled and disabled.
> Add maintenance mode before enabling a module

- test/features/user.site_manager.feature
- test/features/widgets.feature
Issue: CIVIC-4888
1. **widgets.feature** - still two scenarios failing do to speed of CircleCI, need to add 'Wait' 
2. **user.site_manager.feature** - client sites may be using the custom fonts option so separating the test out as customizable to be skipped on client sites
> Update tests for client site issues CIVIC-4888

- CHANGELOG.txt
- dkan.install
Issue: https://jira.govdelivery.com/browse/CIVIC-5550
Module dkan dataset api is obsolote we need to disable and enable open data schema map.
1.  Enable dkan dataset api and open data schema map. We have conflicts between both modules.
> Disable dkan dataset api and enable open data schema #CIVIC-5550

- modules/dkan/dkan_workflow/modules/views_dkan_workflow_tree/views_dkan_workflow_tree.info
If we have enable views_dkan_workflow_tree we can have problems because use functions from workflow_moderation but isn't a dependecy module.
1.  Enable views_dkan_workflow_tree and workflow_moderation is disable.
> Add dependecy worbench moderation to views_dkan_workflow_tree

- CHANGELOG.txt
- test/features/workflow.feature
Issue: CIVIC-5625.
In workflow.feature we have a test with the step: `Then I wait for "Performed Publish on 3 items" ` it could potentially fail in siteswhere there already exists nodes marked as Stale Review.
What we did to fix it was:
- Change nodes names to include a test word to filter by it.
- Add steps for filtering the results and make appear an specific amount of items (in this case just those three).
> Add a filter in workflow.feature to avoid issues in sites where there are nodes that already exists.

- README.md
Just points the docs links in the readme to the new DKAN documentation site. There should be no broken links in the README now.
> Point README links to new docs site

- CHANGELOG.txt
- modules/dkan/dkan_workflow/dkan_workflow.install
- modules/dkan/dkan_workflow/modules/dkan_workflow_permissions/dkan_workflow_permissions.install
Issue:  CIVIC-5641
A client site was not passing workflow tests due to the roleassign_roles variable not getting updated from the hook_enable in dkan_workflow_permissions, moving the code to dkan_workflow fixes this issue.
> Move the roleassign_roles variable update to dkan_workflow.install  CIVIC-5641

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_roles_perms/dkan_sitewide_roles_perms.features.user_permission.inc
- test/features/theme.admin.feature
- themes/nuboot_radix/theme-settings.php
Issue: https://jira.govdelivery.com/browse/CIVIC-5648
Site manager can't change settings about site information.
1. Try to access to admin/config/system/site-information to change site information fields (site name, slogan, e-mail address)
> Allow change site information info on theme settings page 5648

- CHANGELOG.txt
- test/features/topics.feature
Issue: 5771
Client sites that don't have the Featured Topics block in the homepage have this test failing: https://github.com/NuCivic/dkan/blob/7.x-1.x/test/features/topics.feature#L17
> Add a tag @defaultHomepage to make a topic test skippable.

- dkan.profile
DKAN should support PHP 5.3. dkan.profile uses unnecessary PHP5+ array syntax.
> Remove PHP5-only syntax from dkan.profile

- CHANGELOG.txt
- themes/nuboot_radix/includes/panel.inc
Issue: CIVIC-5564
Fixes an error that appears on the front page after an upgrade to 1.13, observed on Pantheon.
UDPATE: confirmed on other invironments.
h2. To reproduce:
1. Build DKAN from a 1.12 tag (say, `7.x-1.12.13`)
2. Check out tag 7.x-1.13 and rebuild (if using ahoy, `git checkout 7.x-1-13`, `ahoy drush remake`
3. Run `drush updatedb`
4. Navigate to the front page. You should see an error message about `$front_nid` not being a declared variable
h2. QA steps
* Reproduce using steps above
* Check out this branch. Error should be gone
> Fix error message on front page after 1.13 upgrade

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
Issue: CIVIC-4456
Updated DKAN api link to use the RTD documentation page instead of the docs.getdkan.com
1.  Go to a dataset page like dataset/wisconsin-polling-places
2. Look in the 'Other access' box in the sidebar left
3. Click on the link "DKAN API"
4. You'll be redirected to the page docs.getdkan.com
1.  Go to a dataset page like dataset/wisconsin-polling-places
2. Look in the 'Other access' box in the sidebar left
3. Click on the link "DKAN API"
4. You'll be redirected to the page dkan.readthedocs.io
> Update DKAN api link to use the RTD documentation page.

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
Issue: CIVIC-5775
Error: `Uncaught ReferenceError: L is not defined`
Change in the library name causing the data extent block to not function properly.
1. View a dataset with a geographical spacial value (dataset/london-deprivation-index)
https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-1731.probo.build/dataset/london-deprivation-index
> Fix dkan extent block with revised library name CIVIC-5775

- docs/releases/notes/1.13.md
CIVIC-5798 
Upgrading DKAN to 1.13 can cause certain front page blocks to disspear, as their machine names have changed. It's unlikely that anyone is using these in their front page in production, as they're just default content, but improving the upgrade instructions just in case.
Also adding quote marks and the TRUE parameter to the "conversion function" to more closely reflect usage for front page conversion.
> Better upgrade instructions for 1.13

- test/features/resource.all.feature
- test/features/widgets.feature
Issue: CIVIC-5746
Clients that disable the main menu will fail two tests that require the main menu links, adding a tag so we can skip these tests when we need to.
> Add @no-main-menu tag to tests that require the main menu CIVIC-5746

- test/features/dataset.all.feature
Some Scenarios were using "DKAN Test" on searches and that made tests fail son some client sites that had content with "Test" as part of the name on Resources or Datasets.
The name of the content used on tests was changed from "DKAN Test" to "DKANTest" to avoid this.
> Improved tests

- CHANGELOG.txt
- drupal-org.make
- modules/dkan/dkan_topics/dkan_topics.make
- test/features/home.feature
Issue: CIVIC-5955 & CIVIC-5964
1. Fix branding on the 1.12 branch
2. Remove dataproxy option from chart source type field
3. Update test on copyright
4. Remove patch for views, no longer applies after views upgrade to 3.15 https://github.com/NuCivic/dkan_dataset/pull/298
Confirm the copyright line says `Powered by DKAN, a project of Granicus` and the links are correct
1. Create a chart
2. Under Load Data, the source type field should only display CSV and Google Spreadsheet as options.
> 1.12.x updates CIVIC-5955

- CHANGELOG.txt
- drupal-org.make
Issue: CIVIC-2768 CIVIC-5964
Update visualization entity to 7.x-1.1
Both 1.12 and 1.13 will use visualization_entity 1.1, once dkan 1.14 is released we will switch to using the same tag name as the dkan core tag
1. Create a chart
2. Under Load Data, the source type field should only display CSV and Google Spreadsheet as options.
> Update visualization_entity to 1.1 CIVIC-2768

- CHANGELOG.txt
- drupal-org.make
Issue: https://jira.govdelivery.com/browse/CIVIC-5965
We need to update service to 3.19. The last version fix some problems with security.
> Security update for services module #CIVIC-5965

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationTest.php
Issue: CIVIC-5989
h2. Description
Harvesting a POD source is not correctly importing the contact name and contact email.
h2. Acceptance Criteria
1. Fix the harvest to make contact name and contact email supported.
2. Add unit tests for importing contact name and email.
1. Create a harvest source.
2. Harvest
3. **Expected**: Contact name and email are imported in destination dataset.
**Actual**: No contact name and email imported.
> Add Support for Contact Name and Email import in Harvest

- CHANGELOG.txt
- test/features/topics.feature
Issue: CIVIC-5746
topics front page test fails if client site is not using the featured topics block on the front page.
> Update front page test on topics.feature

- docs/components/dataset/usage.rst
Issue: CIVIC-5753
Update documentation of the data dictionary field to clarify it should be a url. 
Review http://docs.getdkan.com/en/latest/components/dataset/usage.html page, confirm that the data dictionary field instructions are clear.
> Update description of data dictionary field CIVIC-5753

- CHANGELOG.txt
- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.views_default.inc
Release glitch
Client sites may have various role ids for the site manager role. The featured groups sort order view has access control set to the role, which will break if the role id is not 4. Need to switch back to a permission.
Tests pass on client site
> Switch access to featured groups sort order view from role to permission

- modules/dkan/dkan_sitewide/dkan_sitewide.info
Issue: CIVIC-6049
Issue: CIVIC-5774
When the update module is enabled we have undefined index errors on the dkan modules.
This can be merged after https://github.com/NuCivic/jenkins_release_n_update_builds/pull/19
> Remove project=dkan from dkan_sitewide.info

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.module
Update argument variable names to match template string.
This updates the argument variable names to match the t() template naming. The argument are missing the "@" sign which is generating messaging like this:
> Key **@license** was automatically generated because doesn't exists in the dataset **@Nursing Home Compare**. Make sure you want to modify the key **@license**
Instead of the expected message:
> Key **license** was automatically generated because doesn't exists in the dataset **Nursing Home Compare**. Make sure you want to modify the key **license**
> Update t() arguments naming scheme

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/data/dkan_harvest_datajson_test_resource_accessurl.json
Issue: CIVIC-6096
The POD schema specification states that each distribution should contain one `accessURL` or `downloadURL`. But currently for POD harvest we only expecting a `downloadURL` and drop the resource from the import if it is not specified. The resource import code have a fully featured URL type detection logic and will manage to properly classify any URL that we pass to be it an `accessURL` or the `downloadURL`.
1. Create a Harvest Source. The Source POD should have resource(s) with only the {{accessURL}} is set.
2. Run harvest on the source.
**Expected**: Dataset created with all the associated resources.
**Actual**: Dataset is created, but the resources with only {{accessURL}} defined are not imported.
1. The harvest should fallback to the {{accessURL}} field if the …
> [CIVIC-6096] Use "accessURL" during resources harvest if "downloadURL" field is not available

- CHANGELOG.txt
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.module
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationTest.php
- test/phpunit/dkan_harvest/data/dkan_harvest_datajson_test_original.json
Issue: CIVIC-6108
As defined by the [POD specification|https://project-open-data.cio.gov/v1.1/schema/#accrualPeriodicity], in addition of the standard ISO 8601 periodical values the `accrualPeriodicity` field can also have the **irregular** value which maps to an undetermined period.
1. Create a POD Harvest Source. The source should have dataset(s) with the `accrualPeriodicity` field set to `irregular`.
2. Harvest the source.
3. **Expected**: The dataset imported should have the correct `field_frequency` value.
**Actual**: `field_frequency` is not correctly set.
* `field_frequency` import during POD harvest should correctly support the `irregular` value.
* Add tests for the `accrualPeriodicity` POD field import.
None that should be needed.
None.
> [CIVIC-6108] Field Frequency Harvest POD integration is missing support for "irregular" value

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/data/dkan_harvest_datajson_test_noissued.json
Issue: CIVIC-6112
As per the [POD schema documentation](https://project-open-data.cio.gov/v1.1/schema/#issued), the `issued` field is not required. Missing this field from a source dataset will not break the harvest process and will not generate any user facing errors. But can lead to a very confusing dataset view page where the `Release Date` will be the date this dataset is harvested which is more recent then the `Modified Date` as parsed from the POD `modified` field.
1. Create a Harvest Source. One of the source dataset should not have the optional {{issued}} POD field.
2. Harvest the source.
3. **Expected**: The destination dataset on Dkan have a `Modified Date` that is equal or more recent then the `Release Date`.
**Actual**: The destination dataset have the `Release Date` more …
> [CIVIC-6112] Set fallback in case of issued field is not provided during POD Harvest

- CHANGELOG.txt
- dkan.install
Re-roll of #1847 
Issue: CIVIC-6057
Existing sites are seeing the markdown toolbar on the data dictionary field after upgrading to 1.13
> Add hook_update to fix markdown toolbar on data dictionary field CIVIC-6057

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationTest.php
Issue: CIVIC-6141
The POD schema specification allows for 4 digit year in the temporal field start and end dates. To have a full date consumable by the `field_temporal_coverage` field we have some logic to set the month and day to January 1st for this type of temporal data. This workaround works well for start date but leads to data loss when applied on end dates.
The fix would be to use the last day of the year (December 31) for end four digits dates.
1.  Create a harvest source. One of the source dataset should have the same 4 digits year as start and end dates.
2. Harvest the source.
**Expected**: The 4 digits year is represented correctly on the start and end dates on the `field_temporal_coverage` display.
**Actual**: Only the first start date is represented.
1. Use last day of the …
> [CIVIC-6141] Use last day of year (December 31) for 4 digits end year during temporal POD field import

- CHANGELOG.txt
- dkan.install
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.info
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.strongarm.inc
Description
===
REF CIVIC-5765
Trying to update the Moderation state property for moderable content types (by
default dataset and resources) is not possible because the Moderation combo box
is squashed.
QA Steps
==
> Update chosen configuration to exclude specific select fields.

- CHANGELOG.txt
- dkan.install
CIVIC-6221
This fixes DKAN sites that did not get their jQuery versions set to 1.10 as expected after upgrading to 1.13. It also removes the `field_modified_source_date` field, which was not removed as expected on some upgrades. 
1. Build DKAN from 1.12.
2. Set jquery version to 1.7.
3. Update to this branch (`113-update-fixes`) HEAD
4. Check jQuery version; should now be 1.10
5. Check to make sure `field_modified_source_date` is not there
> Apply jQuery update correctly on upgrade

- CHANGELOG.txt
- drupal-org.make
CIVIC-6226
Tests should pass and basic QA should reveal no issues. This should be a very low-impact change and we should try to remove restws completely in the next point release.
> Update restws to 2.7

- docs/apis/rest-api.rst
Changed `requet a session cookie` to `request a session cookie`.
Issue: link_to_jira_github_issue
> Fixed spelling

- docs/apis/rest-api.rst
Issue: link_to_jira_github_issue
Line 208 `'field_resources[und][0][target_id]' => 'Madison Polling Places (5)'` was returning a syntax error due to no trailing comma.
I can copy and paste all the examples into a PHP script and run it, and everything will work fine (after only having to change end point urls) with no syntax errors.
1. Collate all examples into one script:
- [Log In and get the Session Cookie](http://dkan.readthedocs.io/en/latest/apis/rest-api.html#log-in-and-get-the-session-cookie)
- [Get the CSRF Token](http://dkan.readthedocs.io/en/latest/apis/rest-api.html#get-the-csrf-token)
- [Create a Resource](http://dkan.readthedocs.io/en/latest/apis/rest-api.html#create-a-resource)
- [Attach a file to a resource](http://dkan.readthedocs.io/en/latest/apis/rest-api.html#attach-a-fil …
> Added trailing comma (,) to array.

- CHANGELOG.txt
- test/behat.circleci.yml
- test/behat.docker.yml
- test/behat.local.demo.yml
- test/behat.yml
Yaml syntax present within behat configuration files are not respecting
the behat spec so if you try to use ruby to parse it, parser complains 
about the percentage sign and other characters starting scalar values.
> Fix yaml syntaxt to make it standard

- CHANGELOG.txt
- modules/dkan/dkan_dataset/dkan_dataset.forms.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.features.field_instance.inc
- test/features/dataset.admin.feature
Issue: CIVIC-6137
Removed required status from the Rights field if the public access level is set to 'none'
> Removed required status from the Rights field if the public access level is set to 'none' CIVIC-6137

- CHANGELOG.txt
- drupal-org.make
Issue: https://jira.govdelivery.com/browse/CIVIC-6041
Adding a large range for axis values can crash the browser if the step value is comparatively small. Example:
- Set range from 0 - 50,000
- Step value is set to 1
- The browser will try to draw 50,000 values on the axis
> Added validation on axis tick settings

- drupal-org.make
A bunch of the external modules -- particularly recline -- are still not pointing to the 1.13.4 branch in the makefile for 1.13.4. Let's get them all synced up.
> Point to 1.13.4 for external modules

- test/features/user.all.feature
REF CIVIC-6115
Adds tags to the tests that require a "log in" link in the toolbar, as this is often hidden.
> Allow users to skip login tests.

- docs/apis/datastore-api.rst
There was a space between the link text and the url, breaking the markdown styling.
> Fixing link styling.

- CHANGELOG.txt
- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
Issue: CIVIC-5980
There is a 'Description:' label on the Harvest Source view page. It is unnecessary and should be removed, especially since we don't use it on any other content type.
1. Create Harvest Source Node with a description.
2. Go the "View" tab for the Harvest Source.
The description should not have a label.
- None needed.
> [CIVIC-5980] Remove description label for Harvest Source node view

- CHANGELOG.txt
- dkan.install
Fix dkan_update_7012 so that if a site is still using a deprecated module, the data is not stripped from the db.
> Fix dkan_update_7012

- CHANGELOG.txt
- drupal-org.make
Issue: CIVIC-6072
When adding the Spatial/Geographic Coverage Area for a Dataset in 1.13 the user will run into an error if they follow these steps:
- Add a polygon to the map
- Switches to the GeoJSON and you'll see just null values recorded
- If you switch back to the map it will not display a map
> Fix shapes in the GeoJSON extent field

- CHANGELOG.txt
- dkan.install
- modules/dkan/dkan_dataset/dkan_dataset.forms.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.strongarm.inc
- modules/dkan/dkan_datastore/modules/dkan_datastore_fast_import/dkan_datastore_fast_import.module
REF CIVIC-6466
Fast File imports has an option for which line endings are used for csv files. One of the options is /n/r for Windows line endings, but the actual characters for Window line endings are /r/n
https://en.wikipedia.org/wiki/Newline
###Steps to Reproduce
* enable fast imports
* navigate to a resource
* manage datastore
* check the options for 'Lines terminated by'
* try to import a file with windows endings using \n\r and it will fail
##Acceptance Criteria
* When fast imports is enabled I should see these options for 'Lines terminated by:'
```
\n (Unix)
\r\n (Windows)
\r (Legacy Mac)
```
* When I use a file with windows line endings, and select \r\n when choosing an option for 'Lines terminated by', then the file should be imported completely.
> Fix windows delimiter for datastore_fast_import.

- docs/components/datastore.rst
Issue: CIVIC-6363.
Fixed the command that needs to be run periodically on a cronjob when using fast import. The documentation says the command is `drush queue-run dkan_datastore_queue`, but that is not ok, we have another queue when we are using fast import, so the right command is `drush queue-run dkan_datastore_fast_import_queue`
> Fix fast import docs.

- modules/dkan/dkan_datastore/includes/DkanDatastore.inc
Issue: None
A strict warning message is displayed when a user access to the datastore saying that the updateFromFileUri() function definition is wrong.
1. Go to any resource page.
2. Go to the "Manage datastore" section and confirm that you see a strict warning saying that the updateFromFileUri() function definition is wrong.
> Fix function definition on DKAN Datastore

- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/circle-behat.rb
- .ahoy/.scripts/config.rb
- CHANGELOG.txt
REF CIVIC-6480
Description
===
We want to run dkan tests on client sites but some client sites will have extensive customizations (HHS) that cause tests to fail in ways we can't adjust for so we need to be able to skip the whole file. Using tags to skip the feature causes a new error because there are no scenarios to run.
Acceptance Criteria
A. Find an argument in behat that avoids the No specifications found at path(s) error when using tags
OR
B. There is a section in the config.yml file to list features to skip when running tests. Something like the following
```
circle:
test_dirs:
- config/tests/features
- dkan/test/features
skip_tags:
- customizable 
- fixme
skip_features:
- dataset.admin.feature
- dataset.author.feature
- dataset.editor.feature
```
> Allow skipping of features test via config.

- CHANGELOG.txt
- drupal-org-core.make
Update Drupal core to 7.55. No changes in functionality expected, as this is merely a maintenance release. Tests passing should be enough to merge.
> Upgrade Drupal to 7.55

- CHANGELOG.txt
- drupal-org.make
When creating a Chart using the lineChart type, any zeros in the data are not displayed. Any following data replaces where the 0s should be displayed. 
- https://github.com/NuCivic/recline.view.nvd3.js/pull/43
> Zeros in data are not displayed on line graph Charts

- CHANGELOG.txt
- drupal-org-core.make
Issue: None
Drupal 7.56 has been released. This PR was created in order to update the Drupal core on DKAN.
> Update Drupal core to 7.56

- .ahoy/.scripts/mysql-reconnect.sh
- .ahoy/dkan.ahoy.yml
Every once in a while the mysql docker container IP changes and this brakes the
connection because settings.php is still pointing to the old IP.  This change
resets the mysql IP in order to avoid this issue.
> Add reconnect step to ahoy dkan drupal-rebuild.

- README.md
Issue: https://github.com/NuCivic/dkan/issues/1185
Small update to README.md, fixes a broken link to the Ticket Template in the contribution guide.
> Issue NuCivic/dkan#1185: Fix broken link to Ticket Template in README

- dkan.install
Fix dkan_update_7012 so that if a site is still using a deprecated module, the data is not stripped from the db.
Using this for a patch do not remove until client site is upgraded to 1.13.4
> Update bad hook update

- .ahoy/.scripts/mysql-reconnect.sh
- CHANGELOG.txt
- docs/apis/rest-api.rst
The current REST API docs are somewhat confusing and inconsistent. This new version provides full examples for almost all CRUD operations a typical integration would want, in a more consistent format.
> Rewrite of REST API docs with more complete, pure HTTP examples

- .ahoy/.scripts/behat-parse-params.rb
- .ahoy/.scripts/circle-behat.rb
- .ahoy/.scripts/config.rb
- .ahoy/.scripts/dkan-lint.sh
- CHANGELOG.txt
- circle.yml
- dkan.install
- dkan.profile
- drupal-org.make
- modules/dkan/dkan_fixtures/modules/dkan_default_content/dkan_default_content.install
- modules/dkan/dkan_fixtures/modules/dkan_default_content/dkan_default_content.module
- modules/dkan/dkan_migrate_base/dkan_migrate_base.module
- modules/dkan/dkan_topics/dkan_topics.module
- test/dkanextension/src/Drupal/DKANExtension/Context/DatasetContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/HarvestSourceContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANEntityContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/ServicesContext.php
- test/features/dkan_harvest.feature
- test/features/workflow.feature
Description
====
This PR is a duplicate of #2000 that is required because that PR is not applying cleanly to 1.13.4  and dkan_starter.
These changes are to fix bugs discovered in the latest rounds of site upgrades.
1. Fix dkan_bueditor_markdown_install() uses variable before it is initialized.
2. Fix dkan_update_7016 assumes bueditor id is '5' (not always true).
3. Fix dkan_topics_field_formatter_view() does not check if term exists causing drupal to throw.
4. Fix dkan_default_content_disable() call to processRollback() on null.
5. Fix harvest tests do not clean up.
6. #1963: Allow dkanextension to handle custom fields
7. #1938: Allow skipping of features test via config
8. Do not deregister default content migrations on disable.
9. Fix dkan_migrate_base warning wrong type supplied to …
> Fixes issues found on upgrade 1.13.4 for QA site.

- CHANGELOG.txt
- dkan.install
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.strongarm.inc
Issue: None
This PR adds language selectors to the 'chosen_jquery_selector' configuration. This is needed in order for language selectors to display properly when used (ex: GOSA).
> Include language selectors on 'chosen_jquery_selector' config

- .ahoy/tests/behat-parse-params.rb
- test/behat.yml
- test/dkanextension/src/Drupal/DKANExtension/Context/DatasetContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/PODContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANEntityContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/ServicesContext.php
REF CIVIC-6614 nucivic/dkan_starter#332
By passing Context Attributes via configuration we have the option of overriding
them for custom settings and test environments.
See NuCivic/dkan_starter#392 for dkan_starter version of this and more details.
> Add configurable arguments via Behat Contexts.

- docs/introduction/get-dkan.md
- test/features/resource.author.feature
Terminus is Pantheon's recommended way to deploy distros now. Section added to docs with example Terminus commands.
> Document terminus deployment

- test/features/dataset.author.feature
- test/features/leaflet_draw_widget.feature
- test/features/markdown_editor.feature
- test/features/resource.admin.feature
- test/features/resource.author.feature
- test/features/resource.editor.feature
- test/features/search.feature
- test/features/workflow.feature
- Use smaller file for testing datastore
- Update workflow_19 to work when group is required
- Update markdown.feature to work when group is required
- Update leaflet_draw_widget.feature to work when group is required
Testing the datastore functionality often fails on timing, taking too long to import or delete, so switching to a smaller file.
> Modify tests

- test/features/dataset.author.feature
- test/features/resource.author.feature
REF CIVIC-6649
We added the @javascript tag to some scenarios unnecessarily. This makes tests
slower. This PR undoes that change.
> Update scenarios to not use @javascript where possible.

- test/behat.yml
- test/dkanextension/src/Drupal/DKANExtension/Context/RawDKANEntityContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/ServicesContext.php
Fix bug where autopopulation fails either because:
(1) The field is made to be required via form_api_alter
(2) The field is set but is empty.
(3) The field label is not properly mapped in behat.yml
REF CIVIC-6552
QA Steps
===
> Fix dkanextension does not autopopulate as expected.

- test/features/resource.admin.feature
- test/features/resource.author.feature
- test/features/resource.editor.feature
If you edit a resource that has an existing datastore table and add a new file you will run into the 'unknown records' issue. This causes tests to fail. Adding the @datastore tag will clear out the table after a test so the next one can start fresh.
1. Add a resource and import file to the datastore
2. Edit the resource by uploading a different file.
3. Confirm you see the 'unknown records' problem
> Add @datastore tag to tests

- docs/apis/rest-api.rst
Issue: CIVIC-5159
Document exists so that API users how how to paginate through the list of nodes.
API users have a way to filter the list by content type (and possibly by other criteria, such as taxonomy terms)
Please update the DKAN REST API module documentation so that it explains fully how to use the /api/dataset/node endpoint.
> Update dkan rest api documentation to include details on pagination CIVIC-5159

- CHANGELOG.txt
Issue: CIVIC-4895
The theme was consolidated long before the consolidation of the other repos and the changelog was not brought over in the process. We should merge in the nuboot_radix changelog entries into the main dkan changelog
The updates to nuboot_radix can be found in the dkan CHANGELOG.txt under the matching release tags
> Consolidate the nuboot_radix CHANGELOG.txt into the dkan CHANGELOG.txt CIVIC-4895

- modules/dkan/dkan_dataset/dkan_dataset.module
- themes/nuboot_radix/templates/node/node--search-result.tpl.php
REF CIVIC-6504
* If an iframe is the first thing in a description, the iframe will be displayed
on search results page.
* If summary is longer than 250 words summary can get cut off mid word.
* Ellipses at end of summary or not possible.
QA Steps
==
> Fix iframe allowed in dataset results summary.

- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.api.php
- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
Adds a hook_datastore_api_field_exclude_alter so that field exclusions can be modified for API queries.
As an admin, I would like to be able to not exclude some of the internal fields used in the datastore API query so they can be used as a primary key for the data.
> Datastore api field exclude alter hook

- dkan.install
REF NuCivic/dkan#1807
Some required variables are being set in installation that are not being set
when upgrading from a previous setting.  This is causing some access issues and
multiple test failures.
AC
==
> Add update hook for admin_views variable set

- themes/nuboot_radix/includes/panel.inc
- themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php
When no hero image is defined for the front page we have issues when we add an X-frame-Options-Header.
@kducharm discovered inline style markup on home page that was causing additional loading of the homepage, making a 403 cached version which apparently doesn't respect the X-Frame-Options in Chrome - which is what the security scanner is using. Solution is to remove the broken markup:
```
<div class="panel-top panel-row" style="background-image:url();background-color:#003366">
```
> Fix hero image variable setup

- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.module
Connects #2153 
When creating a harvest source, only the first override or default value is used, multiple value configurations are ignored.
> Adjust harvest functions to pick up multiple override or default values

- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.license_field.inc
- test/features/dataset.author.feature
REF CIVIC-6648
DKAN is not using the direct URLs for license types. This change updates these
URLs to the more direct URL.
QA Steps:
==
> Update license URLs to use more direct URLs.

- CHANGELOG.txt
- drupal-org-core.make
- drupal-org.make
- modules/dkan/dkan_workflow/dkan_workflow.module
- modules/dkan/dkan_workflow/modules/dkan_workflow_permissions/dkan_workflow_permissions.install
- test/dkanextension/src/Drupal/DKANExtension/Context/WorkflowContext.php
- test/features/workflow.feature
- themes/nuboot_radix/includes/menu.inc
> Apply workbench_moderation patch to fix access to revisions

- CHANGELOG.txt
- drupal-org-core.make
- modules/dkan/dkan_dataset/dkan_dataset.module
- modules/dkan/dkan_workflow/dkan_workflow.module
One of the patches added on (#2174) is actually a d8 patch and not needed since we are checking that workbench_moderation is enabled before we adjust permissions now.
When dkan_workflow is enabled the 'revisions' tab is changed to 'moderate'. When anonymous users are viewing datasets and resources we want it to say 'revisions'. The index value of the revisions link is 1 on all content types except for the resource content type because of the 'back to dataset' link. To keep this adjustment working on resource nodes we need to move the 'back to dataset' link so the index for revisions can be 1 and not 2.
> Move 'back to dataset' link to third position

- CHANGELOG.txt
- drupal-org.make
Updates to contrib modules
* autocomplete_deuxe
* better_exposed_filters
* file_entity
* media
* media_youtube
* tablefield (security update)
* views
> Module version updates

- CHANGELOG.txt
- modules/dkan/dkan_dataset/dkan_dataset.forms.inc
- test/features/dataset.author.feature
- test/features/resource.all.feature
Follow up fix for #2184 
When creating a dataset the user will see the groups field on 'step 2', this should be hidden.
> Fix access to groups field

- CHANGELOG.txt
- modules/dkan/open_data_schema_map_dkan/open_data_schema_map_dkan.features.inc
- test/features/dataset.admin.feature
> Fixes field mapping defaults for open data schema APIs

- modules/dkan/dkan_datastore/dkan_datastore.module
- test/dkanextension/src/Drupal/DKANExtension/Context/DatastoreContext.php
- test/dkanextension/src/Drupal/DKANExtension/Context/PODContext.php
- test/features/resource.admin.feature
- test/features/resource.author.feature
- test/features/resource.editor.feature
- test/features/user.site_manager.feature
* Fixed bug with dkan_datastore_records() not returning FALSE
* Added new Behat step to DatastoreContext.php for calling dkan_datastore_records()
* Modified Behat tests to use this new step in favor of searching for text strings to determine status of datastore
This PR addresses some issues raised in #2183. The modifications to resource behat features will hopefully address the recurring random failures with these tests.
No QA Steps other than to confirm that tests are passing in CI.
Fixes #2183
> Strengthening Datastore Behat Tests (#2183)

- .circleci/config.yml
Connects #2240 
Adds workflows to run PHP 5.6 and PHP7 from CircleCI. By default, pushing a branch will run PHP 5.6 build. Adding "php7" to your branch name will make it build PHP 7.1.
Locally, you can use CircleCI CLI to build php 7 using `circleci build --job=build_php71`
> Add PHP 7.1 / 5.6 Workflows to CircleCI

- CHANGELOG.txt
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
When harvesting non-public or restricted public data the harvest error log will display validation errors for the accessLevel field.
> Fix harvest validation for accessLevel values

- .ahoy/docker.ahoy.yml
Connects #2254 
Docker-compose v2 does not share environment variables among containers any longer. This changes ahoy scripts to use credentials from DB container instead.
> Fix for drupal-rebuild not getting MySQL credentials

- test/features/dataset.author.feature
- test/features/resource.author.feature
The backgrounds used on these two files are unnecessarily large, many scenarios do not need any of the set up content and the time it takes to create and tear down all of this test content takes longer than it takes to run the test. This causes SQLSTATE[23000]: Integrity constraint violation: duplicate entry errors on CircleCi
**dataset.author.feature background**
- 9 users
- 4 groups
- 2 tags
- 9 datasets
- 6 resources
**resource.author.feature background**
- 7 users
- 3 groups
- 2 tags
- 6 datasets
- 15 resources!!
Rather than creating all of this content, lets just create the minimum amount per scenario rather than putting everything in the background.
> Refactor dataset.author.feature and resource.author.feature

- CHANGELOG.txt
- modules/dkan/dkan_workflow/dkan_workflow.info
- modules/dkan/dkan_workflow/dkan_workflow.install
- modules/dkan/dkan_workflow/modules/dkan_workflow_permissions/dkan_workflow_permissions.install
- test/dkanextension/src/Drupal/DKANExtension/Context/WorkflowContext.php
Decouples dependency on dkan_workflow_permissions to allow custom workflow permission module overrides
> Remove dkan_workflow_permissions dependency

- CHANGELOG.txt
- modules/dkan/dkan_dataset/css/dkan_dataset.css
Change the icon used for GeoJSON resources in the dataset resource list. We should add a special GeoJSON icon but for now, let's at least use the JSON icon rather than defaulting to "Data".
> Use JSON icon for GeoJSON format

- .ahoy/.docker/etc/mysql/my.cnf
- .ahoy/docker-compose.common.yml
This switches to the mariadb container (rather than the blinkreaction mysql) and removes a bunch of mysql configuration that was killing performance in docker. With this improvement, site installs and other heavy db operations should run relatively quickly in docker without needing to run through docker-machine, especially in linux.
> Switch to mariadb and remove php conviguration

- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
Checking different datastore outputs on our sites show a sql.debug output.
Import a resource into the datastore. Check the API Url and find the sql-property, eg:
`,"sql":"SELECT t.*\nFROM \n{feeds_datastore_dkan_file_40390} t\nORDER BY t.feeds_flatstore_entry_id ASC\nLIMIT 10 OFFSET 0"}}`
> Remove redundant debug output.

- modules/dkan/dkan_sitewide/dkan_sitewide.views_default.inc
Nice to know how many results you have when comparing content in various environments
Saving changelog update until next patch release.
> Add results count to dkan admin views

- test/features/resource.all.feature
Test fails if site:
- has 'resource' link elsewhere on the page
- has more than 10 results in a search of resource content
These adjustments will allow all sites to use this test.
> Update @resource_all_09 scenario

- docs/admin/index.rst
"Adding New Content" is vital but was previously buried two levels in; page deserves to be accessible in main admin doc tree
> Moving the "Adding New Content" page to main admin doc tree

- drupal-org.make
Coder now asks for a blank line between the initial `<?php` and any code. This patch to features fixes an issue where any generated feature files fail coder due to this new standard.
This patch was used to re-export the features in this commit: 5d8bd06887f7ddeb9c065684a3f2d53361a55d93 , see for example
> Patch features to add new line after <?php

- test/behat.yml
- test/dkanextension/src/Drupal/DKANExtension/Context/DKANContext.php
- test/features/dataset.all.feature
- test/features/datastore.feature
- test/features/group.admin.feature
- test/features/group.author.feature
- test/features/group.editor.feature
- test/features/leaflet_draw_widget.feature
- test/features/theme.admin.feature
- test/features/user.admin.feature
- test/features/user.all.feature
- test/features/user.site_manager.feature
Often tests fail due to **integrity constraint violations** because we are creating more content than needed for many test scenarios and the create/teardown process is not keeping up with the speed of the tests. Lets only create what is needed for the tests and simplify the backgrounds. 
Recently tests are failing due to the admin menu overlaying the field/text that a test is trying to use/view. Adding wait steps to allow the menu to snap to the top do not work so adding a context to hide the menu when it is in the way.
Updating behat.yml to not worry about self-signed SSL when running tests
> Simplify background content on tests

- modules/dkan/dkan_data_dictionary/dkan_data_dictionary.module
- modules/dkan/dkan_data_dictionary/js/dkan_data_dictionary.js
Connects #2340 
This adds functionality to check if uploaded data dictionary files match the following criteria. If all of the following criteria is met the file is considered "valid".
- CSV file format
- Only contains columns specified by https://frictionlessdata.io/specs/table-schema/
- Must contain required columns as specified by https://frictionlessdata.io/specs/table-schema/
If the supplied data dictionary file is considered "valid" the contents of the file will be automatically converted to JSON and added to the accompanying JSON Schema field. 
Prior to QAing this pull request you'll want to create three CSV files to test with using the content below.
Example 1: Valid CSV File Example
```
name,type,description,format,constraints
Name,string,User's name,,
Email,string,User's …
```
> 2340-data-dictionaries-b

- test/features/dkan_harvest.feature
Fixing some broken tests post-circle container changes. Despite valiant efforts the have to just be disabled for now. The harvest feature should pass.
> Get harvest tests passing

- modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.api.php
- modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.module
- modules/dkan/dkan_dataset/tests/dkan_dataset_test.info
- modules/dkan/dkan_dataset/tests/dkan_dataset_test.module
- test/phpunit/dkan_dataset/ApiTest.php
This adds a new hook to the DKAN Dataset REST API module that allows adding to or removing the default validation rules in the module.
The new hook is documented in dkan_dataset_rest_api.api.php.
The fact that the API tests pass should demonstrate that it's working -- this is a developer-facing feature that you would need to write a custom module to test out manually.
I've created this against 7.x-1.x because it is a minor enhancement to existing functionality, with no effect on the database.
> Apply custom validation rules to REST API node creation

- .circleci/config.yml
I discovered that xdebug is on by default in our web and cli containers. I am not sure why it is on by default in our CLI container.
Longer-term it would be good to have it off by default. However adding ``ahoy docker xdebug off`` to the tests shaves a couple of mins off the tests it looks like.
> Stop xdebug in web and cli for tests

- dkan.install
- modules/dkan/dkan_dataset/dkan_dataset.install
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.features.field_instance.inc
- test/features/resource.editor.feature
connects #2495 
Non-harvested datasets should not have values for 
- **harvest source issued** 
- **harvest source modified**
1.  Create a new dataset through the UI. 
2. Check the database and note that there is an entry in the **field_data_field_harvest_source_modified** table for the node.
3. Future edits to the dataset will always use this modified date.
> Change default harvest source modified date to blank

- themes/nuboot_radix/includes/panel.inc
- themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php
- themes/nuboot_radix/theme-settings.php
As a site manager I want to control the height of the hero region.
> Add option to adjust height of the hero region

- .ahoy/.scripts/dkan-test.rb
- .ahoy/dkan.ahoy.yml
- .circleci/config.yml
- .circleci/tests/circle/circle.conf
- CHANGELOG.txt
Additional updates from @acouch 's downstream fixes
> Pull in missing script changes

- .github/PULL_REQUEST_TEMPLATE.md
We're not asking for changelog lines w/PRs anymore, generating those ourselves for releases.
> Remove changelog checkbox from PR template

- test/features/dataset.all.feature
- test/features/search.feature
connects https://github.com/NuCivic/dkan_management/issues/66
https://docs.google.com/spreadsheets/d/19bpU7SGeNWrHssH2_dX7LUOCHjXmzlCBrRRSvLO3nkE/edit#gid=1450917050
Search functionality tests are a common failure, this PR only simplifies background usage and removes duplicate scenarios.
CDT, ND, VA are not indexing new data when testing, this will need to be addressed if it continues in 1.16
`search.feature` and `dataset.all.feature` duplicate many scenarios and tests for facet functionality spend a lot of time building a large background to test a single facet, I'm combining those into a single scenario.
**dataset.all.feature** 
- dataset_all_1: the front page will be custom no point in testing content here
- dataset_all_2: duplicate of search 2
- dataset_all_3, dataset_all_4: These …
> Test improvements

- docs/apis/open-data.rst
We worked on data.json mapping documentation for a  partner today and as part of the work we had to define the mapping between DKAN user facing field label and data.json properties.
The PR includes:
* Small fix on the title pod link (first link of the first table).
* Update POD links to point to the v1.1 documentations.
* Add DKAN field labels.
* Add missing `field_conforms_to` to the dataset fields table.
> Open Data API table documentation tweaks

- dkan.install
- modules/dkan/dkan_datastore/src/LockableDrupalVariables.php
Fixes #2482 
**QA:**
1) In a DKAN built with 7.x-1.x move a resource to the datastore.
2) Save a copy of the db
3) Get the code from this branch
4) Rebuild the site with the new code (I used "ahoy dkan reinstall")
5) Load the previously saved database
6) Run "drush updb"
7) The datastore for the resource in the old site should work with the new codebase
> Datastore upgrade path

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.module
- test/features/search.feature
Fixes https://github.com/GetDKAN/dkan/issues/2484
Changes 404 behavior to produce a working search initially set to the bad URL. Also changes the header search box behavior to search whole site, not just datasets.
- Type in a url that does not exist, when on the 404 page, try to use the search block in the header
- Confirm the search is not performed
- Now go to an existing page, use the search block in the header
- Confirm that the results are filtered to only include datasets
> Add redirect to search page on 404 status

- CHANGELOG.txt
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.license_field.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.module
We support a couple of Dkan installs in Spanish. This is a simple patch to wrap a number of user facing strings with the standard t() function. 
The changes should be strait forward but this would be a bit tricky to test with the default Dkan setup since multilingual is not yet part of it. We worked on a [Dkan module (dkan_l10n_es_co)](https://github.com/angrycactus/dkan_l10n_es_co) that enables the spanish language but  requires a number of i18n Drupal modules.
> Wrap Dkan defined string to improve multilingual support

- modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.module
We are currently validating required fields and the options for multi-select fields in a single handler. To allow greater flexibility, we should separate those into 2 separate handlers.
> More granular field validation for datasets and resources.

- modules/dkan/dkan_dataset/css/dkan_dataset.css
small css update for clients allowing ppt/pptx files
- Create a resource with https://cnra-assets.s3.amazonaws.com/resources/27c66899-ed33-4b29-93f4-2f0fecaa59cb/dsm2usersgroupmtg06192018.pptx
- Confirm you see the pptx icon and not the generic 'data' icon
> Update css for ppt/pptx files

- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.module
- test/features/group.admin.feature
- test/features/group.all.feature
- test/features/group.editor.feature
connects #2558
- Add users to a group
- View the group page
- Confirm you do not see the member info at the bottom of the Group block
> Remove group member count and link from group page

- modules/dkan/dkan_datastore/dkan_datastore.module
- modules/dkan/dkan_datastore/dkan_datastore.pages.inc
- modules/dkan/dkan_datastore/src/Pages.php
- modules/dkan/dkan_datastore/src/Resource.php
Fixes #2619 
Improve the UX of datastore import form and related pages by making the interface a single-page form.
(Normal state upon install)
* Currently no way to set default importer, which was part of original acceptance criteria
* Config object now made on node creation. It's made for _any_ resource, not just ones with CSV files
* Still lacking help text
> Datastore one-step form

- modules/dkan/dkan_sitewide/dkan_sitewide.module
Fixes #2537
When on the Available Updates page, you should not see
```
* Warning: Invalid argument supplied for foreach() in theme_update_report() (line 53 of /var/www/docroot/modules/update/update.report.inc).
* Warning: sort() expects parameter 1 to be array, null given in theme_update_report() (line 182 of /var/www/docroot/modules/update/update.report.inc).
* Warning: implode(): Invalid arguments passed in theme_update_report() (line 193 of /var/www/docroot/modules/update/update.report.inc).
```
> Work-around for version check until the version strategy is determined

- docs/introduction/about.md
Made the bundle names actually appear in italics, and fixed spelling of "choropleth."
> Minor documentation fixes

- drupal-org.make
- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.module
- test/features/dataset.editor.feature
- test/features/group.author.feature
- test/features/group.content_creator.feature
- test/features/group.editor.feature
- test/features/resource.editor.feature
connects #2630
connects #2574
Group roles (member, administrator member) are confusing site managers, these roles should be handled entirely behind the scenes so that site managers don't have to worry about them.
- When a user is assigned to a group from the user profile page, they are only in a pending state. You need to go to the group UI to set the user to 'active'. This is resolved by upgrading OG to 2.10
- The group administrator role should only be assigned to editors or site managers since it involves the ability to edit other user's content. This issue is addressed by adding a check before assigning the group administrator role.
> Automate group role assignments

- test/features/workflow.feature
#2578 should have caused a test failure, but because we were both setting up the background incorrectly and not checking the body text, the test was passing. This fixes the test.
* The `@worfklow_19` test should _fail_ if it's written correctly now.
This is a weird one because it should be merged despite failing test. Immediately after we can rebase #2656 which should now have that test _passing_ and merge it.
> Fix test for workflow draft display that was giving false positive

- docs/components/dataset/usage.rst
- docs/development/custom_file_extensions.rst
- docs/development/index.rst
- modules/dkan/dkan_dataset/dkan_dataset.admin.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.module
Currently custom file extensions are added to custom_config with a hook_form_alter() and when updates are made to DKAN the downstream sites do not get those updates as the override holds true.
By adding a UI where site managers can make adjustments it is easy to get new updates and make changes without a code change.
> Add UI to change allowed extensions

- drupal-org.make
- modules/dkan/dkan_datastore/dkan_datastore.module
- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
- modules/dkan/dkan_datastore/src/LockableDrupalVariables.php
- modules/dkan/dkan_datastore/src/Manager/Manager.php
- modules/dkan/dkan_datastore/src/Manager/ManagerInterface.php
- modules/dkan/dkan_datastore/src/Page/Component/Status.php
- modules/dkan/dkan_datastore/src/Page/Page.php
- modules/dkan/dkan_datastore/src/Resource.php
- test/features/resource.admin.feature
- test/features/resource.author.feature
- test/features/resource.editor.feature
Connects #2684
**QA**
- Create a resource with a large file, like https://data.ca.gov/sites/default/files/SafeToSwim_2018-09-04.csv
- Start a datastore import from the UI
- Run cron from drush
- Go back to the UI, you should see that the datastore is in progress and a stop button should be available
- Press the stop button
- A message will let you know that the import will be stopped soon
- Refres the page
- The status should now be paused
> Pause Import

- modules/dkan/dkan_migrate_base/dkan_migrate_base.migrate.inc
```
Migration failed with source plugin exception: <em
class="placeholder">A non-numeric value encountered
```
default content fails to build on php 7.1
> Fix 'non-numeric value encountered' error

- .ahoy/docker-compose.common.yml
- .circleci/config.yml
- modules/dkan/dkan_datastore/includes/DkanDatastore.inc
This PR is a test to see the performance difference between php 5.6 and php 7 to help evaluate updating to PHP 7. The dockerfile for this is here: https://github.com/GetDKAN/dkan-docker/blob/master/.docker/php7-cli/Dockerfile
I screwed up the conifg of the PHP7 cli so will have to wait to try an actual test.
> Update to PHP7 CLI Container

- dkan.install
In some builds we get an undefined function error for dkan_misc_variables_set() on this update. Not sure why it never came up before but this fixes it.
> Include dkan.profile to prevent undefined function in update

- modules/dkan/dkan_workflow/dkan_workflow.module
This keeps anon content from being viewable when dkan_worfklow is turned on. It also brings back the "revision" tab.
1. Turn on dkan_worfklow
2. Create an unpublished node and remove the user. See that it is viewable by anon.
Fixes #2728
> Revision fix

- modules/dkan/dkan_environment/dkan_environment.module
Acquia uses 'test' to refer to its staging environment so updating the lingo here to match
> Change 'stage' to 'test' in dkan_environment

- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
```
Notice: Only variables should be passed by reference in dkan_datastore_api_query() (line 361 of /var/www/dkan/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module).
Notice: Only variables should be passed by reference in dkan_datastore_api_query() (line 362 of /var/www/dkan/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module).
Notice: Only variables should be passed by reference in dkan_datastore_api_sort() (line 711 of /var/www/dkan/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module).
Notice: Only variables should be passed by reference in dkan_datastore_api_sort() (line 714 of /var/www/dkan/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module).
Warning: Invalid argument …
```
> Fix Only variables should be passed by reference in dkan_datastore_api

- modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.license_field.inc
- test/features/dataset.author.feature
Re-run of #2052 
DKAN is not using the direct URLs for license types. This change updates these
URLs to the more direct URL.
QA Steps:
==
> Use direct license url

- modules/dkan/dkan_dataset/dkan_dataset.module
```
Trying to get property of non-object in dkan_dataset_preview_url_cartodb() (line 1066 of /var/www/dkan/modules/dkan/dkan_dataset/dkan_dataset.module).
```
Missing CartoDB Preview buttons
1. Go to `/admin/dkan/dataset_preview` and enable CartoDB preview option for geojson files.
2. Create a resource with this file: http://data-cdfw.opendata.arcgis.com/datasets/3920d5a1ff0f4af3b5540b0cf084c1af_0.geojson
3. Fill in the 'Format' field with `geojson` and save.
4. View the resource, confirm you see the error above and do NOT see the CartoDB Preview button next to the Download button.
> Fix cartodb preview error

- modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module
The ``dkan_datastore_api_debug`` function expect a ``SelectQuery`` object. Yet there is no protection against anything else being passed and breaking things.
This PR fixes that.
> Object check in the datastore_api_debug function.

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
connects #2577
The `dkan_allowed_extensions()` function (added in #2664 is the way to go when overriding resources allowed extensions. During a harvest a check on the allowed extensions is done to honor the user setting. This PR will update this check (done in HarvestMigration::prepareResourceHelper) to use `dkan_allowed_extensions()` instead of querying the field settings. 
Step-by-step instructions for reproducing the bug:
1. Add harvest source that have resources with extensions that are not part of the default field setting but allowed via the `dkan_allowed_extensions()`.
2. Run Harvest on the source.
**Expected**:
All the resources are harvested and imported correctly.
**Currently**:
Resources with non default extensions introduced via `dkan_allowed_extensions()` fail to be …
> Use dkan_allowed_extensions() during harvest

- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.module
Harvest sources with datasets `identifier` fields that ends with "/" (for example `http://dx.doi.org/10.7927/H4PZ56R2/`) will result in an empty generated identifier during the Harvest. 
This PR tweaks the `dkan_harvest_datajson_prepare_item_id` function to account for this case and return the last non empty segment of the `identifier`.
1. Harvest a source that have a dataset with an `identifier` that is a URL that ends with a "/" (in the following example the `identifier` is "http://demo.getdkan.com/90a2b708-7fea-4b92-8aee-43c4cfdd5f48/").
```json
{
"@type": "dcat:Dataset",
"accessLevel": "public",
"contactPoint": {
"fn": "admin",
"hasEmail": "mailto:admin@example.com"
},
"description": "<p>Polling places in the state of Wisconsin</p>",
"distribution": [
{
"@type": "dcat:Distribution", …
```
> Support harvest dataset source identifiers that ends with a '/'

- docs/apis/rest-api.rst
Added a line to documentation for REST API to specify no boolean greater-than or lesser-than operators.
> Adding boolean disclaimer

- docs/apis/datastore-api.rst
In https://docs.getdkan.com/en/latest/apis/datastore-api.html the description of aggregation functions min and max is wrong, we have:
```
min (string) – field to compute the maximum
max (string) – field to compute the minimum
```
> Fixed description of aggregation functions min and max in docs.

- drupal-org-core.make
[SA-CORE-2019-002](https://www.drupal.org/sa-core-2019-002) is a critical security vulnerability (although it is doubtful it presents a real risk to DKAN sites).
> Update Drupal Core to 7.62

- drupal-org-core.make
This is a hotfix release for a regression affecting some Drush installations that was introduced by the fix for SA-CORE-2019-002. No other fixes are included.
> Upgrade drupal to 7.63

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
Connects #2797 
When harvesting from a Socrata source (e.g. https://data.medicare.gov/data.json or https://data.ftb.ca.gov/data.json), the resources are named based on the filename producing resources with titles like `rows.csv`, `rows.json` and similar.
1.  Create a new harvest source using https://data.medicare.gov/data.json and filter by `identifier` = `https://data.medicare.gov/api/views/twwm-t8ug` and harvest the datasets.
2. Go to the imported dataset and confirm the resources names are based on the filename:
> If there is no resource title, use format instead of remote file name.

- modules/dkan/dkan_dataset/dkan_dataset.module
When harvesting we don't know what format the issued and modified dates will be in.
1.  Create a harvest with https://data.cnra.ca.gov/data.json, filter by identifier = 46c9d40b-fbb5-4ea0-9437-f84138d0b966, and harvest
2. Check the errors tab, you will see an error like 'The modified value is not a valid ISO 8601 Date (2018-08-09T17:49:15.225557)'
> Update date validator to add check for dates with time

- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
When adding resources with remote files, the filesize is not always determined correctly, sometimes we get a reported filesize really small and the actual size is completely different.
For example adding a resource with this remote file https://data.chhs.ca.gov/dataset/e0216fbb-3739-4d92-9630-88d9f5686ac6/resource/cdb50347-6fe1-456e-a336-d7daf0aba595/download/road-traffic-injuries-2002-2010.csv We get the resource listed as 15.62MB (and when you download the file it is actually 132.9MB)
- If the file is remote then in the resource page, in the `Additional Information` block shows the filesize as `unknown`.
1. Create a resource with a remote file, for example https://data.chhs.ca.gov/dataset/e0216fbb-3739-4d92-9630-88d9f5686ac6/resource/cdb50347-6fe1-456e-a336-d7daf0aba595/download/road-tra …
> Show filesize as unknown for remote files.

- drupal-org.make
connects #2827
Easy to cause a deadlock if a non-INSERT write operation is more likely to not match any row because the INSERT part is yet to come on the transaction. Don’t do it or use REPLACE INTO or use READ-COMMITTED transaction isolation.
1. Create a draft
2. note the db_update is issued before any records for that nid are inserted
SEE: https://www.drupal.org/project/workbench_moderation/issues/2252871
and : https://www.percona.com/blog/2013/12/12/one-more-innodb-gap-lock-to-avoid/
> Add patch to workbench_moderation

- modules/dkan/dkan_dataset/dkan_dataset.drush.inc
Fixes #2825 
Running `drush ddrp` will find all duplicate dataset revisions from the same timestamp, and reduce them to a single revision. You can limit the number done in one run using `--node-max` and `--revision-max` options.
> Drush command for revision prune

- modules/dkan/dkan_harvest/dkan_harvest.drush.inc
Connects #2828 
Added suport for --feedback on dkan-harvest and dkan-harvest-migrate commands.
When running harvest if the source has a large amount of datasets and the import process is long, then it can last a long time (even more than 15 minutes) without any progress message, which when running over SSH may be an issue because of closed connections by remote host.
Here we're adding support for the `--feedback` options to the `drush dkan-harvest` and `drush dkan-harvest-migrate` commands to print progress messages after X amount if items processed or seconds passed. Also, added a default of 5 min in case the `--feedback` option is not specified.
1. Create a harvest source using https://data.cnra.ca.gov/data.json, add a filter for `publisher.name` to be `California Department of Water …
> Support for --feedback on dkan-harvest and dkan-harvest-migrate commands.

- modules/dkan/dkan_datastore/dkan_datastore.drush.inc
The ghost datastore tables are those for which there doesn't exist a related node, for example there exist a table `feeds_datastore_dkan_file_10000` but there isn't a node with id `10000`. Here we're adding a new drush command `drush dkan-datastore-delete-ghost-tables` with alias `drush dkan-datastore-dgt` to find ghost datastore tables and delete them.
- When you run `drush dkan-datastore-drop-orphan-tables` or `drush dkan-datastore-dot` you'll get the following behaviour:
Connects NuCivic/dkan_management#171
> Drush command for deleting orphaned legacy datastore tables

- drupal-org.make
- modules/dkan/dkan_dataset/dkan_dataset.module
connects #2826 
When harvesting, all resources that are connected to a dataset are removed and recreated. The reason is that there is no unique identifier that can link the distribution info to a specific resource, any of the known values could be changed upstream.
The _dkan_dataset_node_update_ function will add a new revision for the dataset in the node_revision table for each resource. When harvesting large sources (1,000 datasets) and each dataset has 3-18 resources, the node_revision table is hammered with more revisions than necessary.
By skipping the dataset_changelog step, we will limit the revision rows to one for each resource and a single revision for the dataset.
1. create a harvest source from http://janette.dkandemo.nuamsdev.com/data.json
identifier: …
> Skip dataset changelog when harvesting

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
- modules/dkan/dkan_harvest/dkan_harvest.module
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.module
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationTest.php
connects #2824
When a harvest source is temporarily unavailable, all content from that harvest is unpublished and marked as 'orphaned'. On large harvests this can mean huge amounts of unnecessary processing that fails to finish before the next harvest and the source is available again.
Let's instead just leave the content as-is. If the source is truly gone, the catalog maintainer can delete the content via the Harvest UI.
**missing source**
1.  Create a harvest source from https://s3.amazonaws.com/dkan-default-content-files/files/data_harvest_orphan_test.json, and run the harvest.
2. Log in to S3 and make the file private
3. Re-run the harvest, note that rather than unpublishing all of the datasets, you only get the error message:
> Items to import is 0. Looks like source is missing. No …
> Handle missing harvest source without mass un-publishing all content from the source.

- drupal-org.make
sandbox module is not accessible: You won't be able to pull or push project code via HTTPS until you create a personal access token on your account
> Switch to forked version of font_icon_select module

- themes/nuboot_radix/assets/css/nuboot_radix.style.css
- themes/nuboot_radix/scss/components/_harvest.scss
Connects #2847 
Long strings in sidebar should wrap more gracefully.
As a site manager, I'd like to specify harvests with long filters or excludes, without the resulting text overflowing the left sidebar into search results. For example look at http://andrew.dkandemo.nuamsdev.com/harvest_source/cotest
1.  Add a harvest source with long filter or excludes, for example `license` set to ` http://opendefinition.org/licenses/odc-odbl/`, or `accessURL` set to http://www.cha.com/CHA/_Resources/New%20DataBank.aspx`, in those cases the text overflows the left sidebar.
> Wrap words on harvest summary sidebar.

- drupal-org.make
Security update of services to 3.24 because of https://www.drupal.org/sa-contrib-2019-043
> Security update services to 3.24.

- docs/apis/datastore-api.rst
The function "count" is a function already supported by the datastore API but we didn't have that in the docs, so I'm adding that here.
> Added "count" to the list of functions supported on datastore api.

- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
Connects #2850 
Description. If mediaType is defined, use its respective extension as the format for resources harvested.
As a site manager harvesting from a remote JSON source, I want resources that are created to use a resource type that is specified by the mediaType in the JSON, when it is specified, so that in cases where the JSON and remote server mimetype conflict, the resulting resource is correctly typed according to what the JSON intends.
1. Create a harvest from https://bythenumbers.sco.ca.gov/data.json
2. Confirm that some resources in the JSON use "mediaType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
3. Confirm that these resources show up as type "html" or "Web page", though, if downloaded, they're XLSX files
> Allow mediaType to specify resource type during Harvest

- docs/components/datastore.rst
- docs/conf.py
- docs/releases/notes/1.16.4.md
- docs/releases/notes/1.16.5.md
- docs/releases/notes/1.16.6.md
- docs/releases/notes/1.16.7.md
- docs/releases/notes/1.16.8.md
- docs/releases/notes/1.16.9.md
- docs/releases/notes/index.rst
- modules/dkan/dkan_datastore/dkan_datastore.api.php
- modules/dkan/dkan_datastore/src/Manager/Manager.php
- test/phpunit/dkan_datastore/DkanDatastoreTest.php
If in a site we need to execute any steps right after the import to datastore process, right now we don't have an easy way to do it, so in this PR we are introducing a new hook. This hook is called hook_datastore_post_import and it is fired when an import process is completed.
Right now, the dkan datastore tables don't have a primary key field, which may lead to issues when someone needs to index the items from a datastore, so in this PR we're also altering the datastore table schema to include a serial `entry_id` field which will work as the primary key.
> Import manager improvements

- drupal-org-core.make
Security advisory for Drupal core - Moderately critical - Third-party libraries
https://www.drupal.org/sa-core-2019-007
> Security update for Drupal to 7.67 (SA-CORE-2019-007)

- drupal-org.make
Security scans detected network activity when passing a URL to the search_api page. This patch to globalredirect prevents `is_dir()` from running on an external url, which in conjunction with remote_stream_wrapper module will cause a network request to be sent and received from the webserver to a potentially malicious URL.
> Patch globalredirect to fix network issue

- modules/dkan/dkan_workflow/dkan_workflow.module
Add @acouch 's fix for revision permissions.
As a site manager I would like the option to not allow anonymous access to revisions.
1.  Uncheck the permissions 'view revision history' and 'view node revisions' from the anonymous role
2. View a dataset that has revisions as Anonymous, confirm that you can still view the 'Revisions' tab
> Fix hard-coded revisions access for anonymous

- modules/dkan/dkan_datastore/dkan_datastore.drush.inc
On https://github.com/GetDKAN/dkan/pull/2839 we introduced a command for deleting orphan tables for legacy tables. During switch to new datastore all tables were converted from `feeds_datastore_dkan_file_*` to `dkan_datastore_*` but the command was still using all table pattern and right now when we run it on a client site with datastores it just throws an error saying there are no datastore tables which is not accurate.
1. Create a datastore table for a nid that doesn't exist, for example `dkan_datastore_000`.
2. Run the command `drush dkan-datastore-dot`.
3. It returns a message saying "There are currently no datastore tables on this site."
> Use right table to delete orphans.

- modules/dkan/dkan_datastore/src/LockableDrupalVariables.php
> Update the datastore lock code

- modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc
Make Page Title reflect dataset/resource content.
> Make Page Title reflect dataset/resource content.

- modules/dkan/dkan_workflow/views/workbench_moderation.view.inc
As part of https://github.com/GetDKAN/dkan/pull/2879 we included a new tab in the workbench UI to delete current revisions for unpublished nodes (deleting the nodes completely). It has an issue because there is a user filter being applied so the administrators can't moderate them. In this PR we are removing the filter.
1. Log in as an administrator
2. Make sure there is at least one unpublished node with a revision in the site.
3. The tab "Unpublished nodes draft" in admin/workbench shows 0 items.
> Remove user field on unpublished nodes tab on workbench moderation UI.

- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/DatajsonHarvestMigrationScenariosTest.php
- test/phpunit/dkan_harvest/data/dkan_harvest_datajson_test_temporal.json
Harvest sources https://data.cdc.gov/data.json with temporal coverage dates that use dashes as separator are failing with the following error:
```
Error: Call to a member function getTimestamp() on null in       [error]
DatajsonHarvestMigration->prepareRow() (line 201 of
dkan/modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc).
Error: Call to a member function getTimestamp() on null in DatajsonHarvestMigration->prepareRow() (line 201 of dkan/modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc).
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: DateTime::__construct(): Failed to parse time string
(1899-2017) at position 6 (0): Unexpected character in …
```
> Harvest support range dates separated by dashes

- docs/components/datastore.rst
Suggested code for changing primary key on datastore tables was not correct, it was dependant on a specific database name, we're fixing that here.
> Fixed documentation about hook_update code for changing primary key on datastore tables.

- themes/nuboot_radix/assets/css/nuboot_radix.style.css
- themes/nuboot_radix/scss/components/_harvest.scss
1. run a harvest with errors
2. confirm the toggle bar on the error page has a background color
> Add background color to toggle handle

- modules/dkan/dkan_harvest/dkan_harvest.module
Hide groups and datastore messages during harvest runs and from the status page right after it finishes, because those messages are not helpful for the user when multiple datasets/resources are added during harvest.
1. Create a harvest source from https://open.fda.gov/data.json. Click through to "Harvest Now".
2. Once the harvest has completed, note that there are a large number of messages in green, some of them are related to nodes (like  "Node 43 doesn't have a proper file path.") but some don't have an ID so nothing is actionable from "This filemime type (application/zip) can be added as a resource, but cannot be imported to our datastore." or "Groups were updated on 1 resource(s).".
> Hide some harvest messages

- docs/apis/datastore-api.rst
- docs/apis/rest-api.rst
This PR documents the API for controlling the new datastore, which is available via the "Dataset REST API" (not the Datastore API itself, which is only a read API used for queries). This documents the changes added in #2519.
> Document Datastore functions in REST API

- modules/dkan/dkan_harvest/dkan_harvest.migrate.inc
On https://github.com/GetDKAN/dkan/pull/2829 we avoided mass-orphaning datasets when the source was not available, but we still have issues for those sources which cache has been deleted for some reason.
1. Create a harvest source from https://s3.amazonaws.com/dkan-default-content-files/files/data_harvest_orphan_test.json, and run the harvest, all items should be published.
2. Log in to S3 and make the file private
3. Re-run the harvest, the items should not be imported and they should stay published.
4. Delete the cache for your harvest source, you can do it by deleting the directory of your source inside of dkan-harvest-cache folder inside of files. Re-run the harvest, you'll see all the datasets are unpublished and are shown in an orphaned state on the dashboard.
```
Looks like the …
```
> Avoid importing/orphaning when cache is not present for unavailable sources.

- drupal-org-core.make
Mystery missing home page might be related to 
`Warning: class_parents(): object or string expected in panels_panel_context_render()`
> Add patch for NULL controller class

- modules/dkan/dkan_workflow/modules/views_dkan_workflow_tree/views_dkan_workflow_tree.module
Specify behavior on dkan workflow moderation set state action to avoid extra node_save.
1. Log in as a Workflow Contributor, create a new draft for some node and set its state as "Needs Review".
2. Log in as a Workflow Supervisor, go to "My Workbench" page, go to "Needs Review" tab, you should see the draft created in step 1.
3. As a Workflow Supervisor, from the "My Workbench" page, publish the draft using the vbo button.
4. Go to the node page, the changes made are not visible.
5. If you go to the "Moderate" page of the node you'll see two new revisions, the first one is the one which should be published (it contains the changes made) but the second is the one published and set as current:
> Workflow moderation issues when publishing via 

- drupal-org.make
Security update: https://www.drupal.org/sa-contrib-2019-065
> Upgrade imagecache_actions to 1.11

- dkan.install
Connects https://github.com/GetDKAN/dkan/issues/2802
We need to disable the Feeds module now that it's not used by DKAN Datastore.  This update hook does this.
> disable feeds modules

- docs/components/index.rst
- docs/components/periodic-updates.rst
- modules/dkan/dkan_periodic_updates/dkan_periodic_updates.info
- modules/dkan/dkan_periodic_updates/dkan_periodic_updates.module
- test/phpunit/dkan_periodic_updates/DkanPeriodicUpdatesTest.php
- test/phpunit/dkan_periodic_updates/data/test_manifest.csv
- test/phpunit/phpunit.xml
Added dkan_periodic_updates module.
As a site manager I can upload a manifest for a periodic import of resources.
There should be an administrative page where user can upload the manifest, which is a csv file with format resource_id,frequency,file_url.
The file_url will be used to download the file in a temporary directory, then that file will be used to update the resource with the resource_id specified.
The frequency can be daily, weekly or monthly.
- Go to `admin/dkan/periodic-updates`:
- Go to `admin/dkan/periodic-updates/status`:
- For every updated resource check:
Note: documentation as added and also PHP Unit tests.
> Implement periodic updates functionality

- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
Nightly harvest failing with `Call to a member function getTimestamp() on null in       [error]
DatajsonHarvestMigration->prepareRow() (line 207 of
/mnt/www/html/healthdatagov/dkan/modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc`
test on: https://data.chhs.ca.gov/data.json
identifier: "1e1e2904-1bfb-448c-97e1-cf3e228c9159",
temporal: "7/1/1997 - 06/30/2019",
Proper temporal format is: "1997-07-01/2019-06-30"
> This field should contain an interval of time defined by the start and end dates for which the dataset is applicable. Dates should be formatted as pairs of {start datetime/end datetime} in the ISO 8601 format. ISO 8601 specifies that datetimes can be formatted in a number of ways, including a simple four-digit year (eg. 2013) to a much more …
> Fix Call to a member function getTimestamp() on null error

- dkan.install
- drupal-org.make
The current ODSM mapping pages are hard or impossible to load. This cuts out some code that is too recursive and adds [Fast Token Browser](https://www.drupal.org/project/fast_token_browser) to improve page usability and performance. Some documentation of how to use obscure ODSM token hacks may be lost. 
1. On current version of DKAN try to edit an ODSM API. Observe poor performance or broken page.
> Upgrade ODSM and enable fast token browser

- drupal-org.make
- modules/dkan/dkan_dataset/css/dkan_dataset.css
- modules/dkan/dkan_dataset/dkan_dataset.theme.inc
- modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc
- patches/filehash-uploaded-files-only-option.patch
- test/dkanextension/src/Drupal/DKANExtension/Context/ResourceContext.php
- test/features/resource.all.feature
- test/phpunit/dkan_dataset/ResourceFileHashTest.php
- test/phpunit/phpunit.xml
This gives site admins the option of adding hashes to downloadable files. It adds the Filehash module (https://www.drupal.org/project/filehash) to the dkan build. It also applies two hashes to the Filehash module. One adds SHA-512 to the available hash algorithms. The other adds the option of only hashing uploaded files.
If an admin enables the module and selects one or more hash algorithms, a resource file's hash(es) will be displayed below the file name on dataset pages and in the 'Additional Information' block on  resource pages. The display consists of the name of the algorithm (e.g 'md5', 'sha512'), followed by the hash in an input box. The box contains any overflow and makes it easy to copy the entire hash.
As the maintainer of an open data portal, I want to give my users the …
> Add file hash option

- modules/dkan/dkan_dataset/dkan_dataset.module
This PR changes the logic of how DKAN determines whether to create a "revision log" update to a dataset when a resource is changed. We get a lot of extra revisions to datasets based on changes to resources. Rather than trying to check if the update happened during a harvest, this simply checks if the resource revision is more than a minute older than the dataset's updated date. If not, it's not worth recording.
This should provide more consistency and accuracy, and reduce extra revisions created through automated processes. 
Finally, this removes the queue functionality and makes the update immediately. If this creates much longer wait times for harvests to finish we can revisit, but as implemented, the queueing defeats the whole purpose of the revision logging! If the logging is queued …
> Change the way we're handling dataset resource updates to changed time

- modules/dkan/dkan_datastore/dkan_datastore.pages.inc
see https://github.com/NuCivic/healthdata/issues/1155
Why are we printing the file? Can we just always pass the link?
> Move check for file size into the proxy function

- Jenkinsfile
- scripts/release-upload-assets.php
To start doing automatic packaging of DKAN on releases, adding a Jenkinsfile and php packaging script. Adds version info and removes scripts and docs for a downloadable release. (Note: removing the docs is new; we can remove this but I don't think we really need to be distributing them with the releases.)
Also creates a PR for a DROPS release
The asset files uploaded to the [jenkins20](https://github.com/GetDKAN/dkan/releases/tag/jenkins20) release were automatically generated and uploaded. Check the files and confirm they look as expected.
Check GetDKAN/dkan-drops-7#95, generated by the same tag
Delete any "jenkins*" releases and tags from the github repo.
Delete GetDKAN/dkan-drops-7#95
> Add release script and Jenkinsfile

- modules/dkan/dkan_harvest/dkan_harvest.module
When a harvest cache doesn't exist, the harvest source preview page calls a batch to generate it. When the batch is done, it loads the preview page. If the cache can't be created, this creates an infinite loop.
This PR checks that  the Content URI is reachable, and if the header is available, checks that it's a json response. If either check fails, it displays a message instead of triggering the batch
1.  Create a harvest source with an invalid source URL. A batch display will keep flashing until you browse away from the page
- Create a test Harvest Source with an invalid URL and save. Confirm that a message appears and it is appropriate. 
- Change the URL one that goes to a non-json page. Confirm that an appropriate message appears.
- Try valid JSON URLs (including, if possible, one that …
> Prevent infinite loop in Harvest Source preview page

- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.facetapi_defaults.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.features.field_instance.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.features.inc
- modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.views_default.inc
If group descriptions are over 200 characters, they are truncated on the Groups page
1.  Go to /groups. If using sample data, see "State Economic Council".
1. Edit a group. 
2. Click 'Edit summary' and add a summary description.
3. Press Save.
4. Go to /groups and confirm that the summary description is displayed.
Also make sure that the changes to the dkan_dataset_groups feature don't include any unintended sde-effects.
> Add summary option to Group description.

- drupal-org.make
Bug introduced on facetapi 1.6. 
Facets block titles are shown even when the facet is empty, here we're patching facetapi with https://www.drupal.org/project/facetapi/issues/3084250
- Go to datasets search page.
- If a facet is empty, the title shouldn't appear in the sidebar.
> Patch facetapi to hide block when facet is empty.

- docs/components/datastore.rst
- modules/dkan/dkan_datastore/dkan_datastore.drush.inc
Adds a drush command to remove the datastore config and drop the datastore table for a selected resource
1. Find the node id of a resource with a file in datastore.
2. Run `drush dkan-datastore-delete [node id]`
3. Go to the datastore page for the resource and confirm that the "Data importing" state is "Ready"
> Drush command to remove datastore config and drop table for resource.

- drupal-org.make
Adds a patch to `og_moderation` to fix reversion permissions issue.
1.  Log in as anyone except User 1 with at least an 'editor' role.
2. Go to the Revisions page of any dataset with more than one revision that you have permission to edit.
3. Click 'revert' on one of the earlier revisions.
4. Confirm that you get an 'Access Denied' message.
1. Repeat steps 1 - 3 above.
2. Confirm that you see a confirmation page ("Are you sure you want to revert to the revision...")
3. Click the 'Revert' button.
4. Confirm that the dataset was reverted.
> Patch og_moderation module to allow users to revert nodes.

- modules/dkan/dkan_datastore/dkan_datastore.install
- modules/dkan/dkan_datastore/modules/dkan_datastore_fast_import/dkan_datastore_fast_import.module
- modules/dkan/dkan_datastore/modules/dkan_datastore_fast_import/src/FastImport.php
- modules/dkan/dkan_datastore/modules/dkan_datastore_simple_import/dkan_datastore_simple_import.module
- modules/dkan/dkan_datastore/modules/dkan_datastore_simple_import/src/SimpleImport.php
- modules/dkan/dkan_datastore/src/Manager/CharsetEncoding.php
- modules/dkan/dkan_datastore/src/Manager/Info.php
- modules/dkan/dkan_datastore/src/Manager/Manager.php
- modules/dkan/dkan_datastore/src/Manager/ManagerInterface.php
- modules/dkan/dkan_datastore/src/Page/Component/ManagerConfiguration.php
- modules/dkan/dkan_datastore/src/Page/Page.php
- test/phpunit/dkan_datastore/DkanDatastoreEncodingTest.php
- test/phpunit/dkan_datastore/data/win1252_encoding.csv
- test/phpunit/phpunit.xml
fixes #2901
Description. Adds ability to add non UTF-8 files to datastore.
Currently datastore breaks if the file isn't in UTF-8 . 
This adds a select list of allowed PHP encodings to the datastore form. A user can choose the appropriate encoding for the file.
1. Create a new resource, uploading /dkan/test/phpunit/dkan_datastore/data/win1252_encoding.csv.
2. Note that the data preview displays bad characters in the 'title' field
2. Go to 'Manage Datastore' and select 'Windows-1252' as the Character encoding.
3. Click 'Import'.
4. Confirm that the file imports successfully and the special characters now display properly in data preview
> Datastore char encoding

- modules/dkan/dkan_harvest/includes/HarvestMigration.php
- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc
- test/phpunit/dkan_harvest/data/dkan_harvest_datajson_test_accrualPeriodicity.json
Checks the validity of the accrualPeriodicity field in `prepareRow()`.
If a json harvest has an `accrualPeriodicity` value, that value gets saved to the `frequency` field, even if the value isn't valid for the field.
The pr adds a check to prepare row. If the value is a valid key value for field_frequency, there is no change. If it is a valid display value, it is set to the key value. If it is neither, it is set to null.
1.  Run a harvest against a harvest cache with an invalid value for `accrualPeriodicity`.
2. Browse to the dataset page. The invalid value will be displayed as the frequency.
3. Edit the page. The select value for the frequency field will be set to '- None -'.
1. Create/modify three harvest cache files with `accrualPeriodicity`  fields. 
a. Give one a valid Frequency key …
> Check accrualPeriodicity against list of valid frequency values.

- themes/nuboot_radix/template.php
Adds `aria-hidden="true"` to `<i>` tags in breadcrumbs.
1. Go to any page besides the home page.
2. Inspect the breadcrumb and confirm that `<i>` tags contain the `aria-hidden` attribute.
> Add 'aria-hidden' attribute to i tags in breadcrumbs.

- modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.module
Doesn't create a harvest cache file if the identifier is already being used by a dataset harvested from another harvest source.
- This only checks records harvested from the same source url. `https://example-1.com/27cd-f532` and `https://example-2.com/27cd-f532` are considered different identifiers.
- This won't affect duplicate datasets that have already been harvested.
- It won't affect existing harvest caches either unless they are rerun.
- Because harvest files are excluded only if a dataset with the same identifier already exists, it will still be possible to duplicate datasets by harvesting from drush. If a harvest source is cached before another cached harvest source is migrated, they may contain duplicated content. 
1. Create a harvest source that excludes at least one record.
2. …
> Don't cache harvest records for datasets from another HarvestSource.

- drupal-org.make
This patch addresses two security issues:
1. The moment library, a dependency of [recline.js](https://github.com/getdkan/recline.js), is out of date and contains a possible security issue. This updates to the oldest version (to avoid breaking anything) that contains the security fix.
2. While validation prevents any XSS issues with the default DKAN facets, if custom facets are added they will not be protected. This PR adds a [patch to sanitize all facet arguments](https://www.drupal.org/project/facetapi/issues/2610702).
> Upgrade recline and patch facetapi

- dkan.install
- dkan.profile
- drupal-org.make
jquery 1.10 contains the security issue reported here. It's fixed in 1.12. See http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/ 
Let's see how much havoc it would create to switch.
> Use jquery 1.12 by default
